'use strict';
// lib/generateKickstart.js
// Generates per-host ESXi Kickstart (ks.cfg) files for unattended installation.
// Produced for ISO-based deploys only -- OVA path skips this entirely.
// Each file is named ks-esxi-01.cfg, ks-esxi-02.cfg, etc.

function cidrToMask(cidr) {
  if (!cidr) return '255.255.255.0';
  const bits = parseInt(cidr.split('/')[1] || '24', 10);
  const mask = [];
  for (let i = 0; i < 4; i++) {
    const b = Math.min(bits - i * 8, 8);
    mask.push(b <= 0 ? 0 : 256 - Math.pow(2, 8 - b));
  }
  return mask.join('.');
}

function gatewayFromCidr(cidr) {
  if (!cidr) return null;
  const parts = cidr.split('/')[0].split('.').map(Number);
  parts[3] = 1;
  return parts.join('.');
}

function hostIpFromCidr(cidr, hostIndex) {
  // Assigns .101, .102, ... -- matches vcf-bringup.json and vcf-prep.ps1 conventions
  if (!cidr) return null;
  const parts = cidr.split('/')[0].split('.').map(Number);
  parts[3] = 100 + hostIndex;
  return parts.join('.');
}

function buildKickstartFiles(spec) {
  if (spec.esxiDeployMethod === 'ova') return {};
  const count = spec.nestedCluster?.hostCount || 1;
  const files = {};
  for (let i = 1; i <= count; i++) {
    files[`ks-esxi-${String(i).padStart(2, '0')}.cfg`] = buildKickstartForHost(spec, i);
  }
  return files;
}

function buildKickstartForHost(spec, hostIndex) {
  const nc   = spec.nestedCluster || {};
  const nets = spec.networks || {};
  const dc   = spec.domainController || {};
  const ntp  = spec.ntp || {};

  const mgmtCidr = nets.management?.cidr;
  const vlanId   = nets.management?.vlanId;
  const ip       = hostIpFromCidr(mgmtCidr, hostIndex);
  const mask     = cidrToMask(mgmtCidr);
  const gw       = gatewayFromCidr(mgmtCidr);
  const dns      = (dc.enabled && dc.ipAddress) ? dc.ipAddress : '1.1.1.1';
  const ntpSrc   = ntp.source || 'pool.ntp.org';
  const domain   = dc.domainName || 'lab.local';
  const hostname = `esxi-${hostIndex}.${domain}`;
  const rootpw   = nc.rootPassword || '<REPLACE_ME>';

  const lines = [];

  lines.push('# ESXi Kickstart configuration');
  lines.push(`# Host: ${hostname}  Management IP: ${ip || '<see-management-cidr>'}`)  ;
  lines.push('# Generated by vsphere-lab-wizard');
  lines.push('#');
  lines.push('# Usage -- two options:');
  lines.push('#   A) Wizard serves this file: at the ESXi boot menu press Shift+O and append:');
  lines.push('#        ks=http://<wizard-machine-ip>:3000/api/ks/<session-id>/' + hostIndex);
  lines.push('#      (the wizard prints the exact URL for each host when you run deploy-lab.ps1');
  lines.push('#       with -WizardIp <machine-ip>)');
  lines.push('#   B) Self-serve: copy this file to any HTTP server and use that URL instead.');
  lines.push('');

  lines.push('vmaccepteula');

  if (rootpw === '<REPLACE_ME>') {
    lines.push('# rootpw: no password was set in the wizard -- fill in before use or the install will prompt');
    lines.push('rootpw <REPLACE_ME>');
  } else {
    lines.push(`rootpw ${rootpw}`);
  }

  lines.push('install --firstdisk --overwritevmfs --noreboot');
  lines.push('# Note: --firstdisk targets the first disk the installer sees (the boot VMDK).');
  lines.push('# Additional VMDKs for vSAN/local-ds are added by deploy-lab.ps1 -- do not touch them here.');

  // Network line
  const netArgs = ['--bootproto=static', '--device=vmnic0'];
  if (ip)   netArgs.push(`--ip=${ip}`);
  netArgs.push(`--netmask=${mask}`);
  if (gw)   netArgs.push(`--gateway=${gw}`);
  netArgs.push(`--nameserver=${dns}`);
  netArgs.push(`--hostname=${hostname}`);
  if (vlanId != null && vlanId !== 0) netArgs.push(`--vlanid=${vlanId}`);
  lines.push(`network ${netArgs.join(' ')}`);

  lines.push('reboot');
  lines.push('');

  // %firstboot runs after the first full boot into ESXi -- vim-cmd and esxcli are available
  lines.push('%firstboot --interpreter=busybox');
  lines.push('');
  lines.push('# Enable SSH and make the policy persistent');
  lines.push('vim-cmd hostsvc/enable_ssh');
  lines.push('vim-cmd hostsvc/start_ssh');
  lines.push('esxcli system service policy set --enabled true --service TSM-SSH');
  lines.push('');
  lines.push('# Configure NTP');
  lines.push(`esxcli system ntp set --server=${ntpSrc} --enabled=true`);
  lines.push('esxcli system service policy set --enabled true --service ntpd');
  lines.push('esxcli system service start --service-name ntpd');
  lines.push('');
  lines.push('# Suppress interactive shell warning (cosmetic)');
  lines.push('esxcli system settings advanced set -o /UserVars/SuppressShellWarning -i 1');

  return lines.join('\n');
}

module.exports = { buildKickstartFiles, buildKickstartForHost };
