'use strict';
// lib/generateNsx.js
// Generates NSX-T deployment and configuration scripts.

const NSX_SIZES = {
  small:  { vcpu: 3, vramGB: 12, diskGB: 300 },
  medium: { vcpu: 6, vramGB: 24, diskGB: 300 }
};

const NSX_EDGE_SIZES = {
  small:  { vcpu: 2, vramGB: 4 },
  medium: { vcpu: 4, vramGB: 8 },
  large:  { vcpu: 8, vramGB: 32 }
};

const NSX_TOPOLOGY_LABELS = {
  T0T1:     'T0 + T1 Gateways only',
  T0T1DFW:  'T0 + T1 Gateways + Distributed Firewall',
  full:     'Full (T0 + T1 + DFW + NSX Advanced LB profile)'
};

function buildNsxScripts(spec) {
  const nsx = spec.nsx || {};
  if (!nsx.enabled) return {};

  const scripts = {};

  scripts['nsx-deploy.ps1'] = buildNsxDeploy(spec);
  scripts['nsx-configure.ps1'] = buildNsxConfigure(spec);
  if (nsx.bgpEnabled) {
    scripts['nsx-bgp.ps1'] = buildNsxBgp(spec);
  }

  return scripts;
}

function buildNsxDeploy(spec) {
  const nsx    = spec.nsx;
  const nc     = spec.nestedCluster;
  const nets   = spec.networks;
  const dc     = spec.domainController || {};
  const sz     = NSX_SIZES[nsx.size] || NSX_SIZES.small;

  const mgmtGw   = firstHostInCidr(nets.management?.cidr);
  const mgmtMask = cidrToMask(nets.management?.cidr);
  const nsxIp    = nsx.ipAddress || '<NSX-MANAGER-IP>';
  const dnsIp    = dc.enabled && dc.ipAddress ? dc.ipAddress : '8.8.8.8';
  const ntpIp    = spec.ntp?.source || 'pool.ntp.org';
  const dcName   = nc.datacenterName || 'Lab-DC';
  const cluster  = nc.clusterName || 'mgmt-cluster';

  const lines = [];
  lines.push(`# nsx-deploy.ps1 — Deploy NSX-T Manager`);
  lines.push(`# Generated by vsphere-lab-wizard`);
  lines.push(`#`);
  lines.push(`# NSX Manager size: ${nsx.size} (${sz.vcpu} vCPU / ${sz.vramGB}GB RAM / ${sz.diskGB}GB disk)`);
  lines.push(`# Topology: ${NSX_TOPOLOGY_LABELS[nsx.topology] || nsx.topology}`);
  lines.push(`#`);
  lines.push(`# PREREQUISITES:`);
  lines.push(`#   1. Download NSX-T Manager OVA from Broadcom portal`);
  lines.push(`#      (VMware NSX → My Downloads → NSX-T Data Center)`);
  lines.push(`#   2. vCenter must be deployed and reachable`);
  lines.push(`#   3. Management network must be working`);
  lines.push(`#`);
  lines.push(`# ──────────────────────────────────────────────────────────────`);
  lines.push('');
  lines.push('[CmdletBinding()]');
  lines.push('param(');
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$NsxOvaPath,`);
  lines.push('');
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$NsxAdminPassword,`);
  lines.push('');
  lines.push(`    [string]\$VIServer     = "vcenter.${dc.domainName || 'lab.local'}",`);
  lines.push(`    [string]\$VIUser       = "administrator@${nc.ssoDomain || 'vsphere.local'}",`);
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$VIPassword,`);
  lines.push('');
  lines.push(`    [string]\$NsxVmName    = "lab-nsxmgr",`);
  lines.push(`    [string]\$NsxHostname  = "lab-nsxmgr.${dc.domainName || 'lab.local'}",`);
  lines.push(`    [string]\$NsxIpAddress = "${nsxIp}",`);
  lines.push(`    [string]\$NsxNetmask   = "${mgmtMask}",`);
  lines.push(`    [string]\$NsxGateway   = "${mgmtGw || '192.168.10.1'}",`);
  lines.push(`    [string]\$NsxDns       = "${dnsIp}",`);
  lines.push(`    [string]\$NsxNtp       = "${ntpIp}"`);
  lines.push(')');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('Write-Host "Connecting to vCenter $VIServer..."');
  lines.push('$vc = Connect-VIServer -Server $VIServer -User $VIUser -Password $VIPassword -ErrorAction Stop');
  lines.push('');
  lines.push(`$cluster  = Get-Cluster -Name "${cluster}" -ErrorAction Stop`);
  lines.push(`$datacenter = Get-Datacenter -Name "${dcName}" -ErrorAction Stop`);
  lines.push('$targetHost = ($cluster | Get-VMHost | Sort-Object -Property MemoryUsageMB | Select-Object -First 1)');
  lines.push('$targetDs   = ($targetHost | Get-Datastore | Sort-Object -Property FreeSpaceGB -Descending | Select-Object -First 1)');
  lines.push('');
  lines.push('Write-Host "Target host: $($targetHost.Name)"');
  lines.push('Write-Host "Target datastore: $($targetDs.Name)"');
  lines.push('');
  lines.push('# Load and configure OVF properties');
  lines.push('Write-Host "Configuring NSX OVF properties..."');
  lines.push('$ovfConfig = Get-OvfConfiguration -Ovf $NsxOvaPath');
  lines.push('');
  lines.push('$ovfConfig.Common.nsx_role.Value               = "NSX Manager"');
  lines.push('$ovfConfig.Common.nsx_hostname.Value           = $NsxHostname');
  lines.push('$ovfConfig.Common.nsx_ip_0.Value               = $NsxIpAddress');
  lines.push('$ovfConfig.Common.nsx_netmask_0.Value          = $NsxNetmask');
  lines.push('$ovfConfig.Common.nsx_gateway_0.Value          = $NsxGateway');
  lines.push('$ovfConfig.Common.nsx_dns1_0.Value             = $NsxDns');
  lines.push('$ovfConfig.Common.nsx_ntp_0.Value              = $NsxNtp');
  lines.push('$ovfConfig.Common.nsx_isSSHEnabled.Value       = "True"');
  lines.push('$ovfConfig.Common.nsx_allowSSHRootLogin.Value  = "True"');
  lines.push('$ovfConfig.Common.nsx_passwd_0.Value           = $NsxAdminPassword');
  lines.push('$ovfConfig.Common.nsx_cli_passwd_0.Value       = $NsxAdminPassword');
  lines.push('$ovfConfig.Common.nsx_cli_audit_passwd_0.Value = $NsxAdminPassword');
  lines.push('');
  lines.push('# Set network mapping — NSX Manager connects to the management port group');
  lines.push(`$mgmtPg = Get-VirtualPortGroup -Name "Management" -VirtualSwitch * | Select-Object -First 1`);
  lines.push('$ovfConfig.NetworkMapping.Network.Value = $mgmtPg.Name');
  lines.push('');
  lines.push('Write-Host "Deploying NSX Manager OVA (this takes 5-10 minutes)..."');
  lines.push('$vm = Import-VApp `');
  lines.push('    -Source          $NsxOvaPath `');
  lines.push('    -OvfConfiguration $ovfConfig `');
  lines.push('    -VMHost          $targetHost `');
  lines.push('    -Datastore       $targetDs `');
  lines.push('    -DiskStorageFormat Thin `');
  lines.push('    -Location        $cluster `');
  lines.push('    -Name            $NsxVmName `');
  lines.push('    -ErrorAction     Stop');
  lines.push('');
  lines.push('Write-Host "Powering on NSX Manager..."');
  lines.push('Start-VM -VM $vm | Out-Null');
  lines.push('');
  lines.push('Write-Host "Waiting for NSX Manager to respond (allow 5-8 minutes for first boot)..."');
  lines.push('$maxWait = 600');
  lines.push('$waited  = 0');
  lines.push('do {');
  lines.push('    Start-Sleep -Seconds 15');
  lines.push('    $waited += 15');
  lines.push('    try {');
  lines.push('        $resp = Invoke-WebRequest -Uri "https://$NsxIpAddress/api/v1/node" `');
  lines.push('                    -SkipCertificateCheck -TimeoutSec 5 -ErrorAction Stop');
  lines.push('        if ($resp.StatusCode -eq 200) { break }');
  lines.push('    } catch { }');
  lines.push('    Write-Host "  Still waiting... ($waited/$maxWait s)"');
  lines.push('} while ($waited -lt $maxWait)');
  lines.push('');
  lines.push('if ($waited -ge $maxWait) {');
  lines.push('    Write-Warning "NSX Manager did not become reachable within ${maxWait}s. Check the VM console."');
  lines.push('} else {');
  lines.push('    Write-Host ""');
  lines.push('    Write-Host "NSX Manager is up." -ForegroundColor Green');
  lines.push('    Write-Host "  UI: https://$NsxIpAddress   (admin / <password>)"');
  lines.push('    Write-Host "  Run nsx-configure.ps1 next to register with vCenter and build the topology."');
  lines.push('}');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $vc -Confirm:$false');

  return lines.join('\n');
}

function buildNsxConfigure(spec) {
  const nsx  = spec.nsx;
  const nc   = spec.nestedCluster;
  const nets = spec.networks;
  const dc   = spec.domainController || {};
  const edgeCount = nsx.edgeCount || 1;
  const edgeSz    = NSX_EDGE_SIZES[nsx.edgeSize || 'medium'];

  const nsxIp  = nsx.ipAddress || '<NSX-MANAGER-IP>';
  const mgmtGw = firstHostInCidr(nets.management?.cidr);

  const lines = [];
  lines.push(`# nsx-configure.ps1 — Register NSX-T with vCenter and build ${NSX_TOPOLOGY_LABELS[nsx.topology] || nsx.topology}`);
  lines.push(`# Generated by vsphere-lab-wizard`);
  lines.push(`#`);
  lines.push(`# Run AFTER nsx-deploy.ps1 has completed successfully.`);
  lines.push(`# Uses the NSX REST API (no NSX PowerCLI module required).`);
  lines.push(`#`);
  lines.push(`# ──────────────────────────────────────────────────────────────`);
  lines.push('');
  lines.push('[CmdletBinding()]');
  lines.push('param(');
  lines.push(`    [string]\$NsxHost      = "${nsxIp}",`);
  lines.push(`    [string]\$NsxUser      = "admin",`);
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$NsxPassword,`);
  lines.push(`    [string]\$VCenterFqdn  = "vcenter.${dc.domainName || 'lab.local'}",`);
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$VCenterPassword,`);
  lines.push(`    [string]\$VCenterUser  = "administrator@${nc.ssoDomain || 'vsphere.local'}",`);
  lines.push(`    [int]\$EdgeNodeCount = ${edgeCount},`);
  lines.push(`    [string]\$EdgeNodeSize  = "${nsx.edgeSize || 'medium'}"`);
  lines.push(')');
  lines.push('');
  lines.push('$baseUri = "https://$NsxHost/api/v1"');
  lines.push('$headers = @{ "Content-Type" = "application/json" }');
  lines.push('$creds   = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${NsxUser}:${NsxPassword}"))');
  lines.push('$headers["Authorization"] = "Basic $creds"');
  lines.push('');
  lines.push('function Invoke-NsxApi {');
  lines.push('    param([string]$Method, [string]$Path, [hashtable]$Body = $null)');
  lines.push('    $uri = "$baseUri$Path"');
  lines.push('    $params = @{ Method = $Method; Uri = $uri; Headers = $headers; SkipCertificateCheck = $true }');
  lines.push('    if ($Body) { $params["Body"] = ($Body | ConvertTo-Json -Depth 10) }');
  lines.push('    return Invoke-RestMethod @params');
  lines.push('}');
  lines.push('');
  lines.push('# ── 1. Register vCenter as Compute Manager ─────────────────────');
  lines.push('Write-Host "Registering vCenter as compute manager..."');
  lines.push('$vcFingerprint = openssl s_client -connect "${VCenterFqdn}:443" </dev/null 2>/dev/null | openssl x509 -noout -fingerprint -sha256 2>/dev/null');
  lines.push('');
  lines.push('$cmBody = @{');
  lines.push('    display_name = "vCenter"');
  lines.push('    server       = $VCenterFqdn');
  lines.push('    origin_type  = "vCenter"');
  lines.push('    credential   = @{');
  lines.push('        credential_type = "UsernamePasswordLoginCredential"');
  lines.push('        username        = $VCenterUser');
  lines.push('        password        = $VCenterPassword');
  lines.push('        thumbprint      = ""');
  lines.push('    }');
  lines.push('}');
  lines.push('$cm = Invoke-NsxApi -Method POST -Path "/fabric/compute-managers" -Body $cmBody');
  lines.push('Write-Host "  Compute manager id: $($cm.id)"');
  lines.push('');
  lines.push('Start-Sleep -Seconds 30');
  lines.push('');
  lines.push('# ── 2. Create Transport Zone ───────────────────────────────────');
  lines.push('Write-Host "Creating overlay transport zone..."');
  lines.push('$tzBody = @{');
  lines.push('    display_name        = "overlay-tz"');
  lines.push('    transport_type      = "OVERLAY"');
  lines.push('    host_switch_name    = "nsxvswitch"');
  lines.push('}');
  lines.push('$tz = Invoke-NsxApi -Method POST -Path "/transport-zones" -Body $tzBody');
  lines.push('Write-Host "  Transport zone id: $($tz.id)"');
  lines.push('');

  if (nsx.topology === 'T0T1' || nsx.topology === 'T0T1DFW' || nsx.topology === 'full') {
    lines.push('# ── 3. Create Tier-0 Gateway ───────────────────────────────────');
    lines.push('Write-Host "Creating T0 gateway..."');
    lines.push('$t0Body = @{');
    lines.push('    display_name        = "t0-gateway"');
    lines.push('    ha_mode             = "ACTIVE_STANDBY"');
    lines.push('    failover_mode       = "PREEMPTIVE"');
    lines.push('}');
    lines.push('$t0 = Invoke-NsxApi -Method POST -Path "/infra/tier-0s/t0-gateway" -Body $t0Body');
    lines.push('Write-Host "  T0 gateway created"');
    lines.push('');
    lines.push('# ── 4. Create Tier-1 Gateway ───────────────────────────────────');
    lines.push('Write-Host "Creating T1 gateway..."');
    lines.push('$t1Body = @{');
    lines.push('    display_name        = "t1-gateway"');
    lines.push('    tier0_path          = "/infra/tier-0s/t0-gateway"');
    lines.push('    route_advertisement_types = @("TIER1_CONNECTED", "TIER1_STATIC_ROUTES")');
    lines.push('}');
    lines.push('$t1 = Invoke-NsxApi -Method POST -Path "/infra/tier-1s/t1-gateway" -Body $t1Body');
    lines.push('Write-Host "  T1 gateway created"');
    lines.push('');
  }

  if (nsx.topology === 'T0T1DFW' || nsx.topology === 'full') {
    lines.push('# ── 5. Enable Distributed Firewall ────────────────────────────');
    lines.push('Write-Host "Enabling Distributed Firewall..."');
    lines.push('$dfwPolicy = @{');
    lines.push('    display_name = "default-dfw-policy"');
    lines.push('    sequence_number = 10');
    lines.push('    rules = @()');
    lines.push('}');
    lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/domains/default/security-policies/default-dfw-policy" -Body $dfwPolicy | Out-Null');
    lines.push('Write-Host "  DFW default policy created"');
    lines.push('');
  }

  // ── Edge Cluster (run after deploying edge node(s) manually from NSX UI) ──
  lines.push('');
  lines.push(`# ── Edge Cluster (deploy ${edgeCount} edge node(s) from NSX UI first) ─────────────────`);
  lines.push(`# Edge node size: ${nsx.edgeSize || 'medium'} (${edgeSz.vcpu} vCPU / ${edgeSz.vramGB} GB)`);
  lines.push(`# Steps: NSX UI → System → Fabric → Nodes → Edge Transport Nodes → Add`);
  lines.push(`#   Form factor: ${nsx.edgeSize || 'medium'}, connect to overlay transport zone "overlay-tz"`);
  lines.push(`#   Deploy ${edgeCount} node(s), wait until status = "Success", then run this section.`);
  lines.push('#');
  lines.push(`Write-Host "Querying deployed edge transport nodes..."`);
  lines.push(`$edges = (Invoke-NsxApi -Method GET -Path "/fabric/nodes?resource_type=EdgeNode" ).results`);
  lines.push(`Write-Host "  Found \$(\$edges.Count) edge node(s)"`);
  lines.push('');
  lines.push(`if (\$edges.Count -lt \$EdgeNodeCount) {`);
  lines.push(`    Write-Warning "Expected \$EdgeNodeCount edge node(s) but found \$(\$edges.Count). Deploy edge node(s) from the NSX UI first, then re-run."`);
  lines.push(`} else {`);
  lines.push(`    \$members = \$edges[0..(\$EdgeNodeCount - 1)] | ForEach-Object { @{ transport_node_id = \$_.id } }`);
  lines.push(`    \$ecBody = @{`);
  lines.push(`        display_name = "edge-cluster-01"`);
  lines.push(`        members      = \$members`);
  lines.push(`    }`);
  lines.push(`    \$ec = Invoke-NsxApi -Method POST -Path "/api/v1/edge-clusters" -Body \$ecBody`);
  lines.push(`    Write-Host "  Edge cluster created: \$(\$ec.id)"`);
  lines.push('');
  lines.push(`    # Attach edge cluster to T0 so datapath is active`);
  lines.push(`    \$t0Patch = @{ edge_cluster_path = "/infra/sites/default/enforcement-points/default/edge-clusters/\$(\$ec.id)" }`);
  lines.push(`    Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway" -Body \$t0Patch | Out-Null`);
  lines.push(`    Write-Host "  T0 gateway attached to edge cluster"`);
  lines.push(`}`);

  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "NSX configuration complete." -ForegroundColor Green');
  if (nsx.bgpEnabled) {
    lines.push('Write-Host "  BGP: run nsx-bgp.ps1 next to configure BGP peering with VyOS."');
  }
  lines.push('Write-Host "  NSX UI: https://' + nsxIp + '"');

  return lines.join('\n');
}

function buildNsxBgp(spec) {
  const nsx  = spec.nsx;
  const nets = spec.networks;
  const vyos = spec.vyos || {};

  const nsxIp   = nsx.ipAddress || '<NSX-MANAGER-IP>';
  const mgmtGw  = firstHostInCidr(nets.management?.cidr);

  const lines = [];
  lines.push(`# nsx-bgp.ps1 — Configure BGP on T0 Gateway for VyOS peering`);
  lines.push(`# Generated by vsphere-lab-wizard`);
  lines.push(`#`);
  lines.push(`# NSX AS: ${nsx.bgpLocalAs}   VyOS AS: ${nsx.bgpPeerAs}`);
  lines.push(`# VyOS peer IP: ${mgmtGw || '<VYOS-IP>'} (first host in management CIDR)`);
  lines.push(`#`);
  lines.push(`# Run AFTER nsx-configure.ps1 and after VyOS BGP is configured.`);
  lines.push(`#`);
  lines.push(`# ──────────────────────────────────────────────────────────────`);
  lines.push('');
  lines.push('[CmdletBinding()]');
  lines.push('param(');
  lines.push(`    [string]\$NsxHost     = "${nsxIp}",`);
  lines.push(`    [string]\$NsxUser     = "admin",`);
  lines.push(`    [Parameter(Mandatory=\$true)]`);
  lines.push(`    [string]\$NsxPassword,`);
  lines.push(`    [int]\$LocalAs        = ${nsx.bgpLocalAs},`);
  lines.push(`    [int]\$PeerAs         = ${nsx.bgpPeerAs},`);
  lines.push(`    [string]\$PeerAddress = "${mgmtGw || '<VYOS-PEER-IP>'}",`);
  lines.push(`    [string]\$RouteAdvert = "${nsx.bgpRouteAdvert || 'all'}"`);
  lines.push(')');
  lines.push('');
  lines.push('$baseUri = "https://$NsxHost/policy/api/v1"');
  lines.push('$headers = @{ "Content-Type" = "application/json" }');
  lines.push('$creds   = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${NsxUser}:${NsxPassword}"))');
  lines.push('$headers["Authorization"] = "Basic $creds"');
  lines.push('');
  lines.push('function Invoke-NsxApi {');
  lines.push('    param([string]$Method, [string]$Path, [hashtable]$Body = $null)');
  lines.push('    $uri = "$baseUri$Path"');
  lines.push('    $params = @{ Method = $Method; Uri = $uri; Headers = $headers; SkipCertificateCheck = $true }');
  lines.push('    if ($Body) { $params["Body"] = ($Body | ConvertTo-Json -Depth 10) }');
  lines.push('    return Invoke-RestMethod @params');
  lines.push('}');
  lines.push('');
  lines.push('# ── Enable BGP on T0 ──────────────────────────────────────────');
  lines.push('Write-Host "Configuring BGP on T0 gateway (AS $LocalAs)..."');
  lines.push('$bgpBody = @{');
  lines.push('    local_as_num    = "$LocalAs"');
  lines.push('    enabled         = $true');
  lines.push('    inter_sr_ibgp   = $false');
  lines.push('    multipath_relax = $false');
  lines.push('    graceful_restart_config = @{');
  lines.push('        mode = "GR_AND_HELPER"');
  lines.push('        timer = @{ restart_timer = 180; recovery_timer = 360 }');
  lines.push('    }');
  lines.push('}');
  lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway/routing/bgp" -Body $bgpBody | Out-Null');
  lines.push('Write-Host "  BGP enabled (AS $LocalAs)"');
  lines.push('');
  lines.push('# ── Add VyOS BGP neighbor ─────────────────────────────────────');
  lines.push('Write-Host "Adding VyOS BGP neighbor $PeerAddress (AS $PeerAs)..."');
  lines.push('$neighborBody = @{');
  lines.push('    neighbor_address    = $PeerAddress');
  lines.push('    remote_as_num       = "$PeerAs"');
  lines.push('    hold_down_time      = 180');
  lines.push('    keep_alive_time     = 60');
  lines.push('    graceful_restart_mode = "GR_AND_HELPER"');
  lines.push('}');
  lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway/routing/bgp/neighbors/$PeerAddress" -Body $neighborBody | Out-Null');
  lines.push('Write-Host "  BGP neighbor $PeerAddress configured"');
  lines.push('');
  lines.push('# ── Route redistribution ──────────────────────────────────────');
  lines.push('Write-Host "Configuring BGP route redistribution..."');
  const redistTypes = [];
  if (nsx.redistConnected !== false) { redistTypes.push('TIER0_CONNECTED'); redistTypes.push('TIER1_CONNECTED'); }
  if (nsx.redistStatic)              redistTypes.push('TIER0_STATIC');
  if (nsx.redistT1Lb)               redistTypes.push('TIER1_LB_VIP');
  const redistArr = redistTypes.length ? redistTypes.map((t) => `"${t}"`).join(', ') : '"TIER0_CONNECTED", "TIER1_CONNECTED"';
  lines.push('$redisBody = @{');
  lines.push('    bgp_enabled = $true');
  lines.push('    rules = @(');
  lines.push(`        @{ name = "bgp-redistribution"; route_redistribution_types = @(${redistArr}) }`);
  lines.push('    )');
  lines.push('}');
  lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway/routing/redistribution-config" -Body $redisBody | Out-Null');
  lines.push('Write-Host "  Route redistribution configured"');
  lines.push('');

  if (nsx.bgpRouteAdvert === 'specific' && nsx.bgpPrefixes && nsx.bgpPrefixes.length > 0) {
    lines.push('# ── BGP outbound prefix list ──────────────────────────────────');
    lines.push('Write-Host "Configuring BGP outbound prefix list..."');
    lines.push('$prefixListBody = @{');
    lines.push('    display_name = "bgp-advertise-list"');
    lines.push('    prefixes = @(');
    nsx.bgpPrefixes.forEach((prefix) => {
      const bits = prefix.split('/')[1] || '24';
      lines.push(`        @{ network = "${prefix}"; action = "PERMIT"; ge = ${bits}; le = ${bits} }`);
    });
    lines.push('    )');
    lines.push('}');
    lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway/prefix-lists/bgp-advertise-list" -Body $prefixListBody | Out-Null');
    lines.push('Write-Host "  Prefix list configured"');
    lines.push('');
    lines.push('# Apply prefix list as outbound filter on VyOS BGP neighbour');
    lines.push('$neighborFilter = @{ out_route_filters = @("/infra/tier-0s/t0-gateway/prefix-lists/bgp-advertise-list") }');
    lines.push('Invoke-NsxApi -Method PATCH -Path "/infra/tier-0s/t0-gateway/routing/bgp/neighbors/$PeerAddress" -Body $neighborFilter | Out-Null');
    lines.push('Write-Host "  Outbound prefix list applied to VyOS neighbour"');
    lines.push('');
  }

  lines.push('Write-Host ""');
  lines.push('Write-Host "BGP configuration complete." -ForegroundColor Green');
  lines.push('Write-Host "  T0 AS: $LocalAs   VyOS peer: $PeerAddress (AS $PeerAs)"');
  lines.push('Write-Host "  Verify session state: NSX UI → Networking → Tier-0 Gateways → BGP"');

  return lines.join('\n');
}

function firstHostInCidr(cidr) {
  if (!cidr) return null;
  const base = cidr.split('/')[0];
  const p = base.split('.').map(Number);
  p[3] = 1;
  return p.join('.');
}

function cidrToMask(cidr) {
  if (!cidr) return '255.255.255.0';
  const bits = parseInt(cidr.split('/')[1] || '24', 10);
  const mask = [];
  for (let i = 0; i < 4; i++) {
    const b = Math.min(bits - i * 8, 8);
    mask.push(b <= 0 ? 0 : (256 - Math.pow(2, 8 - b)));
  }
  return mask.join('.');
}

module.exports = { buildNsxScripts, NSX_SIZES, NSX_TOPOLOGY_LABELS };
