'use strict';
// lib/generateVis.js
//
// Generates vis-deploy.ps1 -- deploys William Lam's VCF Infrastructure
// Services (VIS) Appliance via VMware OVF Tool (ovftool), the same pattern
// as the nested-ESXi/vCenter OVA deploys elsewhere in this codebase (property
// customization on import), but using ovftool specifically since VIS is
// distributed as a single self-contained OVA meant to be deployed that way.
// https://lamw.github.io/vcf-infrastructure-service-appliance/
//
// NOTE ON OVF PROPERTY NAMES: William Lam's own deployment reference
// (deploy_vis_esx.sh) documents these exact configuration variable names --
// VIS_FQDN, VIS_IP, VIS_NETMASK, VIS_GATEWAY, VIS_DNS_SERVER, VIS_DNS_DOMAIN,
// VIS_NTP_SERVER, VIS_ROOT_PASSWORD -- but does not publish the literal OVF
// property IDs those map to inside the OVA descriptor, and OVA property
// names can change between appliance releases. This script uses the
// documented variable names directly as --prop: keys (the overwhelmingly
// common convention for Lam's other appliances). If ovftool reports unknown
// properties at deploy time, run `ovftool "<path-to-vis.ova>"` alone first --
// it prints every available property and its exact ID -- and adjust the
// --prop: flags below to match.

const { firstHostInCidr, cidrToMask } = require('./generateVcf');

function buildVisDeploy(spec) {
  const vis = spec.vis || {};
  if (!vis.enabled) return null;

  const lines = [];
  const nets = spec.networks || {};
  const mgmtCidr = nets.management && nets.management.cidr;

  const visIp = vis.ipAddress || '';
  const gatewayDefault = firstHostInCidr(mgmtCidr) || '192.168.10.1';
  const netmaskDefault = cidrToMask(mgmtCidr);

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push("    Deploy William Lam's VCF Infrastructure Services (VIS) Appliance to nested-esxi-01.");
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by zero-to-hero-lab on ${spec.generatedAt}.`);
  lines.push('    Deploys the VIS OVA via VMware OVF Tool (ovftool) -- ovftool must be');
  lines.push('    installed and on PATH, see PREREQUISITES.md. VIS provides DNS, NTP,');
  lines.push('    DHCP, a software depot, and a container registry for VCF lab');
  lines.push('    deployments, as an alternative to a Windows domain controller.');
  lines.push('');
  lines.push('    Attribution: William Lam (williamlam.com) -- VCF Infrastructure Services Appliance');
  lines.push('    https://lamw.github.io/vcf-infrastructure-service-appliance/');
  lines.push('');
  lines.push('.NOTES');
  lines.push('    Minimum resources (per the appliance\'s own docs): 2 vCPU / 4 GB RAM / 30 GB disk.');
  lines.push(`    VIS IP: ${visIp || '<not set -- fill in lab-config.json or pass -VisIp>'}`);
  lines.push('    If ovftool reports an unknown --prop: key, run `ovftool "<path-to-vis.ova>"`');
  lines.push('    alone first to list this OVA\'s exact property names, then adjust this script.');
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    # Management IP/hostname of nested-esxi-01 (standalone, not in vCenter yet)');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$EsxiHostName,');
  lines.push('');
  lines.push('    [string]$Datastore = "datastore1",');
  lines.push('');
  lines.push('    [string]$MgmtPortGroup = "Nested-Trunk",');
  lines.push('');
  lines.push('    [string]$VisFqdn = "vis.lab.local",');
  lines.push('');
  lines.push(`    [string]$VisIp = "${visIp}",`);
  lines.push('');
  lines.push(`    [string]$VisNetmask = "${netmaskDefault}",`);
  lines.push('');
  lines.push(`    [string]$VisGateway = "${gatewayDefault}",`);
  lines.push('');
  lines.push('    [string]$VisDnsServer = "8.8.8.8",');
  lines.push('');
  lines.push('    [string]$VisDnsDomain = "lab.local",');
  lines.push('');
  lines.push('    [string]$VisNtpServer = "pool.ntp.org",');
  lines.push('');
  lines.push('    # Leave the placeholder to set it manually after first boot instead');
  lines.push('    [string]$VisRootPassword = "<REPLACE_ME>"');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not $VisIp) {');
  lines.push('    throw "No VIS IP address set -- pass -VisIp or fill in the VIS appliance IP address in the wizard."');
  lines.push('}');
  lines.push('');
  lines.push('# --- Load lab-config.json (place it next to this script -- see PREREQUISITES.md) ---');
  lines.push('$LabConfigPath = Join-Path $PSScriptRoot "lab-config.json"');
  lines.push('if (-not (Test-Path -Path $LabConfigPath -PathType Leaf)) {');
  lines.push('    throw "lab-config.json not found at $LabConfigPath. Copy lab-config.json.example (in this same folder) to lab-config.json, fill in your file paths, and re-run."');
  lines.push('}');
  lines.push('$LabConfig = Get-Content -Raw -Path $LabConfigPath | ConvertFrom-Json');
  lines.push('');
  lines.push('$VisOvaPath = $LabConfig.localPaths.visOva');
  lines.push('if (-not $VisOvaPath) {');
  lines.push('    throw "VIS appliance OVA not configured -- set localPaths.visOva in lab-config.json."');
  lines.push('}');
  lines.push('if (-not (Test-Path -Path $VisOvaPath -PathType Leaf)) {');
  lines.push('    throw "VIS appliance OVA not found at \'$VisOvaPath\' (lab-config.json localPaths.visOva). Check the path and try again."');
  lines.push('}');
  lines.push('');
  lines.push('if (-not (Get-Command ovftool -ErrorAction SilentlyContinue)) {');
  lines.push('    throw "ovftool not found on PATH -- install VMware OVF Tool (see PREREQUISITES.md) before running this script."');
  lines.push('}');
  lines.push('');
  lines.push('$esxiCred = Get-Credential -Message "ESXi credentials for $EsxiHostName"');
  lines.push('$esxiUser = $esxiCred.UserName');
  lines.push('$esxiPass = $esxiCred.GetNetworkCredential().Password');
  lines.push('');
  lines.push('Write-Host "Deploying VIS appliance to $EsxiHostName via ovftool..."');
  lines.push('');
  lines.push('$ovftoolArgs = @(');
  lines.push('    "--acceptAllEulas",');
  lines.push('    "--noSSLVerify",');
  lines.push('    "--diskMode=thin",');
  lines.push('    "--datastore=$Datastore",');
  lines.push('    "--network=$MgmtPortGroup",');
  lines.push('    "--name=vis-appliance",');
  lines.push('    "--prop:VIS_FQDN=$VisFqdn",');
  lines.push('    "--prop:VIS_IP=$VisIp",');
  lines.push('    "--prop:VIS_NETMASK=$VisNetmask",');
  lines.push('    "--prop:VIS_GATEWAY=$VisGateway",');
  lines.push('    "--prop:VIS_DNS_SERVER=$VisDnsServer",');
  lines.push('    "--prop:VIS_DNS_DOMAIN=$VisDnsDomain",');
  lines.push('    "--prop:VIS_NTP_SERVER=$VisNtpServer",');
  lines.push('    "--prop:VIS_ROOT_PASSWORD=$VisRootPassword",');
  lines.push('    $VisOvaPath,');
  lines.push('    "vi://${esxiUser}:${esxiPass}@${EsxiHostName}"');
  lines.push(')');
  lines.push('');
  lines.push('& ovftool $ovftoolArgs');
  lines.push('');
  lines.push('if ($LASTEXITCODE -ne 0) {');
  lines.push('    throw "ovftool deployment failed (exit code $LASTEXITCODE) -- see ovftool output above."');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host "VIS appliance deployed. Power it on, then browse to https://$VisIp once first-boot customisation finishes."');
  lines.push('Write-Host "DNS, NTP, DHCP, depot, and registry services are disabled by default -- configure them from the VIS web UI after first boot."');

  return lines.join('\n');
}

module.exports = { buildVisDeploy };
