// lib/generatePowerShell.js
//
// Returns { 'filename.ps1': scriptContent, ... } for each deployment stage.
// The stages must be run in the order they appear here — each one depends on
// the prior stage being complete. lab-design.md explains why.
//
// PowerShell uses $ constantly, so scripts are built as string arrays (no JS
// template-literal interpolation inside PowerShell variable names) to avoid
// escaping bugs. Only real spec values get injected.

const ESXI_GUEST_ID = {
  '9.0':   'vmkernel9Guest',
  '8.0u3': 'vmkernel8Guest',
  '8.0u2': 'vmkernel8Guest',
  '8.0u1': 'vmkernel8Guest'
};

function buildPowerShellScripts(spec) {
  const scripts = {};

  // Insertion order = deployment order
  if (spec.vyos && spec.vyos.enabled) {
    scripts['vyos-deploy.ps1'] = buildVyosDeploy(spec);
  }
  if (spec.domainController && spec.domainController.enabled) {
    scripts['dc-deploy.ps1'] = buildDcDeploy(spec);
  }
  scripts['deploy-lab.ps1'] = buildDeployLab(spec);
  scripts['vcenter-deploy.ps1'] = buildVcenterDeploy(spec);
  if (spec.nestedCluster.vsanEnabled) {
    scripts['vsan-cluster.ps1'] = buildVsanCluster(spec);
  }
  if (spec.workloadVms && spec.workloadVms.enabled && spec.workloadVms.count > 0) {
    scripts['deploy-workloads.ps1'] = buildWorkloadsDeploy(spec);
  }
  if (spec.nestedCluster.memoryTiering && spec.nestedCluster.memoryTiering.enabled) {
    scripts['configure-memory-tiering.ps1'] = buildMemoryTiering(spec);
  }

  const ra = spec.remoteAccess || {};
  if (ra.method === 'ssh_jump' || (ra.method === 'vpn' && ra.vpnType === 'wireguard')) {
    scripts['jumpbox-deploy.ps1'] = buildJumpboxDeploy(spec);
  }
  if (ra.method === 'vpn' && ra.vpnType === 'wireguard') {
    scripts['wireguard-server.sh'] = buildWireGuardSetup(spec);
  }
  if (ra.method === 'vpn' && ra.vpnType === 'vyos_site_to_site') {
    scripts['vyos-site-to-site.conf'] = buildVyosSiteToSite(spec);
  }

  return scripts;
}

// --- Stage 1: VyOS router/firewall VM shell ---

function buildVyosDeploy(spec) {
  const lines = [];
  const nets = spec.networks;
  const vyos = spec.vyos;

  const labPortGroups = [];
  if (nets.management) labPortGroups.push('Nested-Mgmt');
  if (nets.vMotion) labPortGroups.push('Nested-vMotion');
  if (nets.vmTraffic) labPortGroups.push('Nested-VM-Traffic');
  if (spec.nestedCluster.vsanEnabled && nets.vsan) labPortGroups.push('Nested-vSAN');

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Stage 1: Deploy the VyOS virtual router/firewall VM shell.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Run this first. VyOS is the network foundation -- nothing else in the lab');
  lines.push('    has a routable path until the router is up and configured.');
  lines.push('    This script creates the VM shell and attaches the ISO. Boot the VM and');
  lines.push('    run through the VyOS installer and network config manually.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    Network mode: ${vyos.networkMode === 'bgp' ? 'Basic NAT/DHCP/DNS + BGP peering' : 'Basic NAT, DHCP, DNS forwarding'}`);
  lines.push('    VyOS sizing: 2 vCPU, 1GB RAM, 4GB disk');
  lines.push('    eth0 = WAN (connects to $WanPortGroupName, gets upstream access)');
  lines.push(`    eth1..N = lab networks (${labPortGroups.join(', ')})`);
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VIServer,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VMHostName,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$Datastore,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VyosIsoPath,');
  lines.push('');
  lines.push('    # Port group that gives the router its upstream/WAN access');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$WanPortGroupName,');
  lines.push('');
  lines.push('    [string]$VirtualSwitchName = "vSwitch0",');
  lines.push('');
  lines.push('    [string]$VmFolder = "Nested-Lab",');
  lines.push('');
  lines.push('    [string]$VmName = "vyos-router"');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('$cred = Get-Credential -Message "Credentials for $VIServer"');
  lines.push('Connect-VIServer -Server $VIServer -Credential $cred | Out-Null');
  lines.push('');
  lines.push('$vmHost = Get-VMHost -Name $VMHostName');
  lines.push('$ds = Get-Datastore -Name $Datastore');
  lines.push('');
  lines.push('if (-not (Get-Folder -Name $VmFolder -ErrorAction SilentlyContinue)) {');
  lines.push('    $vmFolderParent = Get-Folder -Type VM -NoRecursion | Select-Object -First 1');
  lines.push('    New-Folder -Name $VmFolder -Location $vmFolderParent | Out-Null');
  lines.push('}');
  lines.push('');
  lines.push('if (Get-VM -Name $VmName -ErrorAction SilentlyContinue) {');
  lines.push('    Write-Host "$VmName already exists, skipping."');
  lines.push('    exit 0');
  lines.push('}');
  lines.push('');
  lines.push('$vm = New-VM -Name $VmName `');
  lines.push('    -VMHost $vmHost `');
  lines.push('    -Datastore $ds `');
  lines.push('    -DiskGB 4 `');
  lines.push('    -MemoryGB 1 `');
  lines.push('    -NumCpu 2 `');
  lines.push('    -GuestId "debian11_64Guest" `');
  lines.push('    -Location $VmFolder `');
  lines.push('    -CD');
  lines.push('');
  lines.push('# WAN interface -- connected to the upstream port group');
  lines.push('New-NetworkAdapter -VM $vm -NetworkName $WanPortGroupName -Type Vmxnet3 -StartConnected | Out-Null');
  lines.push('');
  lines.push('# LAN interfaces -- eth1, eth2... in the order listed');
  for (const pg of labPortGroups) {
    lines.push(`New-NetworkAdapter -VM $vm -NetworkName "${pg}" -Type Vmxnet3 -StartConnected | Out-Null`);
  }
  if (vyos.networkMode === 'bgp') {
    lines.push('');
    lines.push('# BGP mode: add more NICs here if you need to peer with additional segments');
  }
  lines.push('');
  if (spec.nestedCluster.legacyCpuCompatibility) {
    lines.push('New-AdvancedSetting -Entity $vm -Name "monitor.allowLegacyCPU" -Value "TRUE" -Confirm:$false | Out-Null');
    lines.push('');
  }
  lines.push('Get-CDDrive -VM $vm | Set-CDDrive -IsoPath $VyosIsoPath -StartConnected $true -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('Write-Host "VyOS VM shell ready: $VmName"');
  lines.push('Write-Host "Power it on, install VyOS, then configure NAT and DHCP before moving to the next stage."');
  if (vyos.networkMode === 'bgp') {
    lines.push('Write-Host ""');
    lines.push('Write-Host "BGP mode: after basic NAT/DHCP works, configure BGP in VyOS:"');
    lines.push('Write-Host "  set protocols bgp system-as <your-ASN>"');
    lines.push('Write-Host "  set protocols bgp neighbor <peer-ip> remote-as <peer-ASN>"');
    lines.push('Write-Host "See lab-design.md for the full config walkthrough."');
  }
  lines.push('');
  lines.push('Disconnect-VIServer -Server $VIServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- Stage 2: Domain controller VM shell ---

function buildDcDeploy(spec) {
  const lines = [];
  const dc = spec.domainController;
  const nets = spec.networks;
  const mgmtVlan = nets.management?.vlanId ?? 0;

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Stage 2: Deploy the Windows domain controller VM shell.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Run this after vyos-deploy.ps1 and after VyOS is configured.');
  lines.push('    The DC must be up and promoted before nested ESXi hosts are installed.');
  lines.push('    Every host points at the DC for DNS and NTP, and vCenter needs DNS to');
  lines.push('    resolve its own FQDN during installation. DC first, everything else after.');
  lines.push('    Install Windows Server manually, then run:');
  lines.push('      Install-WindowsFeature AD-Domain-Services -IncludeManagementTools');
  lines.push(`      Install-ADDSForest -DomainName "${dc.domainName || 'lab.yourdomain.com'}" -SafeModeAdministratorPassword (Read-Host -AsSecureString)`);
  lines.push('');
  lines.push('.NOTES');
  if (dc.domainName) lines.push(`    Domain: ${dc.domainName}`);
  if (dc.ipAddress) lines.push(`    DC IP: ${dc.ipAddress} -- set this as a static IP during Windows setup`);
  lines.push('    DC sizing: 2 vCPU, 4GB RAM, 80GB disk');
  lines.push(`    Network: Nested-Mgmt (VLAN ${mgmtVlan || 'untagged'})`);
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VIServer,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VMHostName,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$Datastore,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$WindowsIsoPath,');
  lines.push('');
  lines.push('    [string]$VmFolder = "Nested-Lab",');
  lines.push('');
  lines.push('    [string]$VmName = "lab-dc-01"');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('$cred = Get-Credential -Message "Credentials for $VIServer"');
  lines.push('Connect-VIServer -Server $VIServer -Credential $cred | Out-Null');
  lines.push('');
  lines.push('$vmHost = Get-VMHost -Name $VMHostName');
  lines.push('$ds = Get-Datastore -Name $Datastore');
  lines.push('');
  lines.push('if (-not (Get-Folder -Name $VmFolder -ErrorAction SilentlyContinue)) {');
  lines.push('    $vmFolderParent = Get-Folder -Type VM -NoRecursion | Select-Object -First 1');
  lines.push('    New-Folder -Name $VmFolder -Location $vmFolderParent | Out-Null');
  lines.push('}');
  lines.push('');
  lines.push('if (Get-VM -Name $VmName -ErrorAction SilentlyContinue) {');
  lines.push('    Write-Host "$VmName already exists, skipping."');
  lines.push('    exit 0');
  lines.push('}');
  lines.push('');
  lines.push('$vm = New-VM -Name $VmName `');
  lines.push('    -VMHost $vmHost `');
  lines.push('    -Datastore $ds `');
  lines.push('    -DiskGB 80 `');
  lines.push('    -MemoryGB 4 `');
  lines.push('    -NumCpu 2 `');
  lines.push('    -GuestId "windows2019srv_64Guest" `');
  lines.push('    -Location $VmFolder `');
  lines.push('    -CD');
  lines.push('');
  lines.push('New-NetworkAdapter -VM $vm -NetworkName "Nested-Mgmt" -Type Vmxnet3 -StartConnected | Out-Null');
  lines.push('');
  if (spec.nestedCluster.legacyCpuCompatibility) {
    lines.push('New-AdvancedSetting -Entity $vm -Name "monitor.allowLegacyCPU" -Value "TRUE" -Confirm:$false | Out-Null');
    lines.push('');
  }
  lines.push('Get-CDDrive -VM $vm | Set-CDDrive -IsoPath $WindowsIsoPath -StartConnected $true -Confirm:$false | Out-Null');
  lines.push('');
  if (dc.ipAddress || dc.domainName) {
    const noteVal = [dc.ipAddress && `IP: ${dc.ipAddress}`, dc.domainName && `Domain: ${dc.domainName}`].filter(Boolean).join('  ');
    lines.push(`Set-VM -VM $vm -Notes "${noteVal}" -Confirm:$false | Out-Null`);
    lines.push('');
  }
  lines.push('Write-Host "DC VM shell ready: $VmName"');
  lines.push('Write-Host "Power it on, install Windows Server, set a static IP, then promote to DC."');
  if (dc.ipAddress) lines.push(`Write-Host "Planned DC IP: ${dc.ipAddress}"`);
  if (dc.domainName) lines.push(`Write-Host "Domain: ${dc.domainName}"`);
  lines.push('Write-Host "Once the DC is up, proceed to deploy-lab.ps1 to build the nested ESXi hosts."');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $VIServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- Stage 3: Port groups + nested ESXi VM shells ---

function buildDeployLab(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const nets = spec.networks;
  const dc = spec.domainController;
  const localDs = spec.localDatastore;
  const versionKey = spec.esxiVersion?.version || null;
  const guestId = ESXI_GUEST_ID[versionKey] || 'vmkernel65Guest';
  const versionLabel = spec.esxiVersion?.label || 'ESXi (version not specified)';

  const portGroups = [];
  if (nets.management?.cidr || nets.management?.vlanId !== null) {
    portGroups.push({ name: 'Nested-Mgmt', vlan: nets.management.vlanId ?? 0 });
  }
  if (nets.vMotion?.cidr || nets.vMotion?.vlanId !== null) {
    portGroups.push({ name: 'Nested-vMotion', vlan: nets.vMotion.vlanId ?? 0 });
  }
  if (nc.vsanEnabled && nets.vsan) {
    portGroups.push({ name: 'Nested-vSAN', vlan: nets.vsan.vlanId ?? 0 });
  }
  if (nets.vmTraffic?.cidr || nets.vmTraffic?.vlanId !== null) {
    portGroups.push({ name: 'Nested-VM-Traffic', vlan: nets.vmTraffic.vlanId ?? 0 });
  }
  if (portGroups.length === 0) {
    portGroups.push({ name: 'Nested-Mgmt', vlan: 0 });
  }

  const prereqs = [];
  if (spec.vyos?.enabled) prereqs.push('vyos-deploy.ps1 (VyOS installed and configured)');
  if (dc.enabled) prereqs.push('dc-deploy.ps1 (DC installed and promoted)');

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push(`    Stage ${prereqs.length + 1}: Port groups and nested ESXi VM shells.`);
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  if (prereqs.length) {
    lines.push(`    Run this after: ${prereqs.join(', ')}.`);
  }
  lines.push('    This script does not install ESXi. Power on each VM, run through the ESXi');
  lines.push('    installer, then proceed to vcenter-deploy.ps1.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    ESXi version: ${versionLabel} (GuestId: ${guestId})`);
  lines.push(`    Nested hosts: ${nc.hostCount} x (${nc.vcpuPerHost} vCPU, ${nc.vramPerHostGB}GB vRAM, ${nc.bootDiskGB}GB boot disk)`);
  const additionalDisks = nc.additionalDisks || [];
  const vsanDisks = additionalDisks.filter((d) => d.purpose === 'vsan_capacity' || d.purpose === 'vsan_cache');
  const localDsDisk = additionalDisks.find((d) => d.purpose === 'local_datastore');
  if (vsanDisks.length > 0) {
    lines.push(`    vSAN disks added per host: ${vsanDisks.map((d) => d.sizeGB + 'GB ' + d.purpose.replace('vsan_', '') + ' VMDK').join(' + ')}`);
    lines.push('    Do NOT format or partition these during ESXi installation -- vsan-cluster.ps1 claims them.');
  }
  if (localDsDisk) {
    lines.push(`    Local datastore: an extra ${localDsDisk.sizeGB}GB VMDK is added to nested-esxi-01 only.`);
    lines.push('    Format it as VMFS during ESXi setup (name it "local-ds").');
    lines.push('    vCenter deploys onto this datastore in vcenter-deploy.ps1.');
  }
  if (dc.enabled && dc.ipAddress) {
    lines.push(`    After installing ESXi on each host, set DNS and NTP to ${dc.ipAddress} (the DC).`);
  }
  // Physical storage inventory
  const storageDev = (spec.physicalHost?.storageDevices || []);
  if (storageDev.length > 0) {
    lines.push('');
    lines.push('    Physical storage inventory:');
    const TYPE_LABEL = { nvme: 'NVMe', sata_ssd: 'SATA SSD', sas_ssd: 'SAS SSD', spinning_disk: 'HDD' };
    storageDev.forEach((d, i) => {
      const capLabel = d.capacityGB >= 1000 ? `${(d.capacityGB / 1000).toFixed(1)}TB` : `${d.capacityGB}GB`;
      lines.push(`    Disk ${i + 1}: ${TYPE_LABEL[d.type] || d.type} ${capLabel}`);
    });
  }
  if (additionalDisks.length > 0) {
    lines.push('');
    lines.push('    Nested host disk layout (additional VMDKs per host):');
    additionalDisks.forEach((d) => {
      const hostsNote = d.purpose === 'local_datastore' ? ' (host 1 only)' : ' (all hosts)';
      lines.push(`    - ${d.sizeGB}GB [${d.purpose}]${hostsNote}`);
    });
  }
  lines.push('    Source spec: lab-spec.json');
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VIServer,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VMHostName,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$Datastore,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$EsxiIsoPath,');
  lines.push('');
  lines.push('    [string]$VirtualSwitchName = "vSwitch0",');
  lines.push('');
  lines.push('    [string]$VmFolder = "Nested-Lab"');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('# --- Connect ---');
  lines.push('$cred = Get-Credential -Message "Credentials for $VIServer"');
  lines.push('Connect-VIServer -Server $VIServer -Credential $cred | Out-Null');
  lines.push('');
  lines.push('$vmHost = Get-VMHost -Name $VMHostName');
  lines.push('$vSwitch = Get-VirtualSwitch -VMHost $vmHost -Name $VirtualSwitchName');
  lines.push('$ds = Get-Datastore -Name $Datastore');
  lines.push('');
  lines.push('if (-not (Get-Folder -Name $VmFolder -ErrorAction SilentlyContinue)) {');
  lines.push('    $vmFolderParent = Get-Folder -Type VM -NoRecursion | Select-Object -First 1');
  lines.push('    New-Folder -Name $VmFolder -Location $vmFolderParent | Out-Null');
  lines.push('}');
  lines.push('');
  lines.push('# --- Port groups for the nested lab ---');
  lines.push('# Promiscuous mode, forged transmits, and MAC address changes must all be allowed.');
  lines.push('# Nested ESXi sends frames from MAC addresses the physical vSwitch never learned,');
  lines.push('# and the parent vSwitch silently drops them unless these three are switched on.');
  lines.push('');
  lines.push('$portGroups = @(');
  for (const pg of portGroups) {
    lines.push(`    @{ Name = "${pg.name}"; VlanId = ${pg.vlan} }`);
  }
  lines.push(')');
  lines.push('');
  lines.push('foreach ($pg in $portGroups) {');
  lines.push('    if (-not (Get-VirtualPortGroup -VirtualSwitch $vSwitch -Name $pg.Name -ErrorAction SilentlyContinue)) {');
  lines.push('        New-VirtualPortGroup -VirtualSwitch $vSwitch -Name $pg.Name -VlanId $pg.VlanId | Out-Null');
  lines.push('    }');
  lines.push('    $pgObj = Get-VirtualPortGroup -VirtualSwitch $vSwitch -Name $pg.Name');
  lines.push('    Get-SecurityPolicy -VirtualPortGroup $pgObj |');
  lines.push('        Set-SecurityPolicy -AllowPromiscuous $true -ForgedTransmits $true -MacChanges $true | Out-Null');
  lines.push('    Write-Host "Port group ready: $($pg.Name) (VLAN $($pg.VlanId))"');
  lines.push('}');
  lines.push('');
  lines.push('# --- Nested ESXi host VMs ---');
  lines.push(`$nestedHostCount = ${nc.hostCount}`);
  lines.push(`$vcpuPerHost = ${nc.vcpuPerHost}`);
  lines.push(`$vramPerHostGB = ${nc.vramPerHostGB}`);
  lines.push(`$bootDiskGB = ${nc.bootDiskGB}`);
  if (additionalDisks.length > 0) {
    lines.push('$additionalDisks = @(');
    additionalDisks.forEach((d) => {
      lines.push(`    @{ SizeGB = ${d.sizeGB}; Purpose = '${d.purpose}' }`);
    });
    lines.push(')');
  }
  lines.push('');
  lines.push('for ($i = 1; $i -le $nestedHostCount; $i++) {');
  lines.push('    $vmName = "nested-esxi-{0:D2}" -f $i');
  lines.push('');
  lines.push('    if (Get-VM -Name $vmName -ErrorAction SilentlyContinue) {');
  lines.push('        Write-Host "$vmName already exists, skipping."');
  lines.push('        continue');
  lines.push('    }');
  lines.push('');
  lines.push('    $vm = New-VM -Name $vmName `');
  lines.push('        -VMHost $vmHost `');
  lines.push('        -Datastore $ds `');
  lines.push('        -DiskGB $bootDiskGB `');
  lines.push('        -MemoryGB $vramPerHostGB `');
  lines.push('        -NumCpu $vcpuPerHost `');
  lines.push(`        -GuestId "${guestId}" \``);
  lines.push('        -Location $VmFolder `');
  lines.push('        -CD');
  lines.push('');
  for (const pg of portGroups) {
    lines.push(`    New-NetworkAdapter -VM $vm -NetworkName "${pg.name}" -Type Vmxnet3 -StartConnected | Out-Null`);
  }
  lines.push('');
  lines.push('    # Nested virtualisation -- needed so this nested ESXi can itself power on VMs');
  lines.push('    New-AdvancedSetting -Entity $vm -Name "vhv.enable" -Value "TRUE" -Confirm:$false | Out-Null');
  lines.push('');
  if (nc.legacyCpuCompatibility) {
    lines.push('    # Legacy CPU compatibility -- needed on some older host CPUs for nested ESXi to boot');
    lines.push('    New-AdvancedSetting -Entity $vm -Name "monitor.allowLegacyCPU" -Value "TRUE" -Confirm:$false | Out-Null');
    lines.push('');
  }
  if (additionalDisks.length > 0) {
    lines.push('    # Additional virtual disks (defined in $additionalDisks above)');
    lines.push('    foreach ($disk in $additionalDisks) {');
    lines.push("        if ($disk.Purpose -eq 'local_datastore' -and $i -ne 1) { continue }");
    lines.push('        New-HardDisk -VM $vm -CapacityGB $disk.SizeGB -StorageFormat Thin -Confirm:$false | Out-Null');
    lines.push('    }');
    lines.push('');
  }
  lines.push('    Get-CDDrive -VM $vm | Set-CDDrive -IsoPath $EsxiIsoPath -StartConnected $true -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('    Write-Host "Created $vmName. Power it on and run through the ESXi installer manually."');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Port groups and VM shells are in place."');
  if (dc.enabled && dc.ipAddress) {
    lines.push(`Write-Host "After installing ESXi: set DNS and NTP to ${dc.ipAddress} on each host."`);
  }
  if (localDs.enabled) {
    lines.push('Write-Host "On nested-esxi-01: format the extra disk as VMFS -- name it local-ds."');
  }
  lines.push('Write-Host "Then proceed to vcenter-deploy.ps1."');
  lines.push('Disconnect-VIServer -Server $VIServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- Stage 4: vCenter VCSA deployment ---

function buildVcenterDeploy(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const nets = spec.networks;
  const dc = spec.domainController;
  const localDs = spec.localDatastore;
  const ra = spec.remoteAccess;

  const deploySize = ra.vcenterDeploymentSize || 'small';
  const dnsServer = dc.enabled && dc.ipAddress ? dc.ipAddress : '8.8.8.8';

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Deploy vCenter VCSA onto nested-esxi-01.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Run this after all nested ESXi hosts are installed and reachable.');
  lines.push('    Connects directly to nested-esxi-01 in standalone mode (vCenter does not');
  lines.push('    exist yet). Detects govc and uses it if available; falls back to PowerCLI.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    Deployment size: ${deploySize}`);
  lines.push(`    DNS for VCSA: ${dnsServer}${dc.enabled ? ' (domain controller)' : ''}`);
  if (localDs.enabled) {
    lines.push('    Target datastore: local-ds on nested-esxi-01');
  }
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    # Management IP/hostname of nested-esxi-01 (standalone, not in vCenter yet)');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$EsxiHostName,');
  lines.push('');
  lines.push(`    [string]$Datastore = "${localDs.enabled ? 'local-ds' : 'datastore1'}",`);
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VcsaOvaPath,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VcenterFqdn,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VcenterIp,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VcenterGateway,');
  lines.push('');
  lines.push(`    [string]$VcenterDnsServer = "${dnsServer}",`);
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [securestring]$VcenterPassword,');
  lines.push('');
  lines.push(`    [string]$DeploymentSize = "${deploySize}",`);
  lines.push('');
  lines.push('    [string]$MgmtPortGroup = "Nested-Mgmt",');
  lines.push('');
  lines.push(`    [string]$SsoDomain = "${nc.ssoDomain || 'vsphere.local'}"`);
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('$plainPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(');
  lines.push('    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($VcenterPassword))');
  lines.push('');
  lines.push('# --- Detect govc vs PowerCLI and deploy accordingly ---');
  lines.push('$govcAvailable = Get-Command govc -ErrorAction SilentlyContinue');
  lines.push('');
  lines.push('if ($govcAvailable) {');
  lines.push('    Write-Host "govc found -- using govc to deploy VCSA"');
  lines.push('');
  lines.push('    $env:GOVC_URL      = "https://$EsxiHostName"');
  lines.push('    $env:GOVC_INSECURE = "true"');
  lines.push('    $esxiCred = Get-Credential -Message "ESXi credentials for $EsxiHostName"');
  lines.push('    $env:GOVC_USERNAME = $esxiCred.UserName');
  lines.push('    $env:GOVC_PASSWORD = $esxiCred.GetNetworkCredential().Password');
  lines.push('');
  lines.push('    $specFile = [System.IO.Path]::GetTempFileName() + ".json"');
  lines.push('    govc import.spec $VcsaOvaPath | ConvertFrom-Json | ForEach-Object {');
  lines.push('        $_.NetworkMapping[0].Network = $MgmtPortGroup');
  lines.push('        $_.DeploymentOption = $DeploymentSize');
  lines.push('        foreach ($p in $_.PropertyMapping) {');
  lines.push('            switch ($p.Key) {');
  lines.push('                "guestinfo.cis.appliance.net.addr"       { $p.Value = $VcenterIp }');
  lines.push('                "guestinfo.cis.appliance.net.gateway"    { $p.Value = $VcenterGateway }');
  lines.push('                "guestinfo.cis.appliance.net.dns.servers"{ $p.Value = $VcenterDnsServer }');
  lines.push('                "guestinfo.cis.appliance.net.pnid"       { $p.Value = $VcenterFqdn }');
  lines.push('                "guestinfo.cis.appliance.net.mode"       { $p.Value = "static" }');
  lines.push('                "guestinfo.cis.appliance.net.addr.family"{ $p.Value = "ipv4" }');
  lines.push('                "guestinfo.cis.appliance.net.prefix"     { $p.Value = "24" }');
  lines.push('                "guestinfo.cis.appliance.root.passwd"    { $p.Value = $plainPassword }');
  lines.push('                "guestinfo.cis.vmdir.password"           { $p.Value = $plainPassword }');
  lines.push('                "guestinfo.cis.vmdir.domain-name"        { $p.Value = $SsoDomain }');
  lines.push('                "guestinfo.cis.deployment.node.type"     { $p.Value = "embedded" }');
  lines.push('                "guestinfo.cis.appliance.ssh.enabled"    { $p.Value = "true" }');
  if (dc.ipAddress) {
    lines.push(`                "guestinfo.cis.appliance.ntp.servers"    { $p.Value = "${dc.ipAddress}" }`);
  }
  lines.push('            }');
  lines.push('        }');
  lines.push('        $_');
  lines.push('    } | ConvertTo-Json -Depth 10 | Set-Content $specFile');
  lines.push('');
  lines.push('    govc import.ova -options $specFile -ds $Datastore -host $EsxiHostName -name "vcenter" $VcsaOvaPath');
  lines.push('    Remove-Item $specFile -Force');
  lines.push('');
  lines.push('    Write-Host "VCSA deployed via govc. Power it on and allow ~20 min for first-boot."');
  lines.push('');
  lines.push('} else {');
  lines.push('    Write-Host "govc not found -- using PowerCLI Import-VApp"');
  lines.push('');
  lines.push('    if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('        throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('    }');
  lines.push('    Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('    $esxiCred = Get-Credential -Message "ESXi credentials for $EsxiHostName"');
  lines.push('    Connect-VIServer -Server $EsxiHostName -Credential $esxiCred | Out-Null');
  lines.push('');
  lines.push('    $vmHost = Get-VMHost -Name $EsxiHostName');
  lines.push('    $ds = Get-Datastore -Name $Datastore');
  lines.push('');
  lines.push('    $ovfConfig = Get-OvfConfiguration -Ovf $VcsaOvaPath');
  lines.push('    $ovfConfig.NetworkMapping.Network_1.Value                           = $MgmtPortGroup');
  lines.push('    $ovfConfig.DeploymentOption.Value                                   = $DeploymentSize');
  lines.push('    $ovfConfig.guestinfo.cis.deployment.node.type.Value                 = "embedded"');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.addr.family.Value            = "ipv4"');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.mode.Value                   = "static"');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.addr.Value                   = $VcenterIp');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.prefix.Value                 = "24"');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.gateway.Value                = $VcenterGateway');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.dns.servers.Value            = $VcenterDnsServer');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.net.pnid.Value                   = $VcenterFqdn');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.root.passwd.Value                = $plainPassword');
  lines.push('    $ovfConfig.guestinfo.cis.vmdir.password.Value                       = $plainPassword');
  lines.push('    $ovfConfig.guestinfo.cis.vmdir.domain-name.Value                    = $SsoDomain');
  lines.push('    $ovfConfig.guestinfo.cis.vmdir.site-name.Value                      = "Default-First-Site"');
  lines.push('    $ovfConfig.guestinfo.cis.appliance.ssh.enabled.Value                = "true"');
  if (dc.ipAddress) {
    lines.push(`    $ovfConfig.guestinfo.cis.appliance.ntp.servers.Value               = "${dc.ipAddress}"`);
  }
  lines.push('');
  lines.push('    Import-VApp -Source $VcsaOvaPath `');
  lines.push('        -OvfConfiguration $ovfConfig `');
  lines.push('        -VMHost $vmHost `');
  lines.push('        -Datastore $ds `');
  lines.push('        -Location (Get-Folder -Type VM -NoRecursion | Select-Object -First 1) `');
  lines.push('        -Name "vcenter" | Out-Null');
  lines.push('');
  lines.push('    Start-VM -VM (Get-VM -Name "vcenter") | Out-Null');
  lines.push('    Write-Host "VCSA deployed and powered on. Allow ~20 min for first-boot."');
  lines.push('');
  lines.push('    Disconnect-VIServer -Server $EsxiHostName -Confirm:$false');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host "vCenter will be available at https://$VcenterFqdn  or  https://$VcenterIp"');
  if (nc.vsanEnabled) {
    lines.push('Write-Host "Once vCenter is ready, proceed to vsan-cluster.ps1."');
  }
  if (spec.workloadVms?.enabled) {
    lines.push('Write-Host "After the cluster is formed, proceed to deploy-workloads.ps1."');
  }
  lines.push('');

  return lines.join('\n');
}

// --- Stage 5: vSAN cluster formation ---

function buildVsanCluster(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const nets = spec.networks;

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Create the vSphere cluster in vCenter and enable vSAN.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Prerequisites: vCenter is deployed and accessible (vcenter-deploy.ps1 done).');
  lines.push('    Connects to vCenter, creates a datacenter and cluster, adds the nested ESXi');
  lines.push('    hosts, and enables vSAN with manual disk claiming so it does not accidentally');
  lines.push('    claim the local-ds disk on host 1.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    Nested hosts to add: ${nc.hostCount}`);
  if (nets.vsan) {
    const vsanNet = [nets.vsan.cidr, nets.vsan.vlanId !== null ? `VLAN ${nets.vsan.vlanId}` : null].filter(Boolean).join(', ');
    lines.push(`    vSAN network: ${vsanNet || 'not set'}`);
  }
  lines.push('    NestedHostIPsCSV: management IPs assigned during ESXi installation, comma-separated');
  lines.push('    e.g. "10.0.71.101,10.0.71.102,10.0.71.103"');
  lines.push(`    vSAN architecture: ${nc.vsanArchitecture || 'esa'} (${nc.vsanArchitecture === 'osa' ? 'two-tier cache+capacity' : 'single-tier, no cache disk'})`);
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VCenterServer,');
  lines.push('');
  lines.push(`    [string]$DatacenterName = "${nc.datacenterName || 'Lab-DC'}",`);
  lines.push('');
  lines.push(`    [string]$ClusterName = "${nc.clusterName || 'mgmt-cluster'}",`);
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$NestedHostIPsCSV');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push(`$vcCred = Get-Credential -Message "vCenter credentials (administrator@${nc.ssoDomain || 'vsphere.local'})"`);
  lines.push('Connect-VIServer -Server $VCenterServer -Credential $vcCred | Out-Null');
  lines.push('');
  lines.push('$nestedHostIPs = $NestedHostIPsCSV -split ","');
  lines.push('');
  lines.push('# --- Datacenter ---');
  lines.push('if (-not (Get-Datacenter -Name $DatacenterName -ErrorAction SilentlyContinue)) {');
  lines.push('    New-Datacenter -Location (Get-Folder -Type Datacenter -NoRecursion | Select-Object -First 1) `');
  lines.push('        -Name $DatacenterName | Out-Null');
  lines.push('    Write-Host "Created datacenter: $DatacenterName"');
  lines.push('}');
  lines.push('$dc = Get-Datacenter -Name $DatacenterName');
  lines.push('');
  lines.push('# --- Cluster with vSAN, manual disk claiming ---');
  lines.push('# Manual claim mode prevents vSAN from grabbing the local-ds disk on host 1.');
  lines.push('if (-not (Get-Cluster -Name $ClusterName -Location $dc -ErrorAction SilentlyContinue)) {');
  lines.push('    New-Cluster -Name $ClusterName -Location $dc `');
  lines.push('        -DrsEnabled -HAEnabled `');
  lines.push('        -VsanEnabled -VsanDiskClaimMode Manual | Out-Null');
  lines.push('    Write-Host "Created cluster: $ClusterName"');
  lines.push('}');
  lines.push('$cluster = Get-Cluster -Name $ClusterName -Location $dc');
  lines.push('');
  lines.push('# --- Add nested hosts ---');
  lines.push('$hostCred = Get-Credential -Message "ESXi root credentials (same password for all nested hosts)"');
  lines.push('');
  lines.push('foreach ($hostIp in $nestedHostIPs) {');
  lines.push('    $hostIp = $hostIp.Trim()');
  lines.push('    if (-not $hostIp) { continue }');
  lines.push('');
  lines.push('    if (Get-VMHost -Name $hostIp -ErrorAction SilentlyContinue) {');
  lines.push('        Write-Host "$hostIp already in inventory, skipping."');
  lines.push('        continue');
  lines.push('    }');
  lines.push('');
  lines.push('    Write-Host "Adding $hostIp to cluster..."');
  lines.push('    Add-VMHost -Name $hostIp -Location $cluster -Credential $hostCred -Force | Out-Null');
  lines.push('    Write-Host "Added: $hostIp"');
  lines.push('}');
  lines.push('');
  lines.push('# --- Report vSAN-eligible disks for manual claiming ---');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Hosts added. Eligible vSAN disks per host:"');
  lines.push('foreach ($vmHost in (Get-Cluster $ClusterName -Location $dc | Get-VMHost)) {');
  lines.push('    $eligible = Get-VMHost $vmHost | Get-VMHostDisk |');
  lines.push('        Where-Object { $_.ExtensionData.Vsan.State -eq "eligible" }');
  lines.push('    Write-Host "  $($vmHost.Name): $($eligible.Count) eligible disk(s)"');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host ""');
  if ((nc.vsanArchitecture || 'esa') === 'esa') {
    lines.push('Write-Host "Claim disks via vCenter UI: Configure > vSAN > Disk Management > Claim unused disks"');
    lines.push('Write-Host "ESA: claim all eligible disks as single-tier capacity — no cache/capacity split."');
  } else {
    lines.push('Write-Host "Claim disks via vCenter UI (Configure > vSAN > Disk Management) or:"');
    lines.push('Write-Host "  OSA: Get-VMHost <host> | Get-VsanEligibleDisk | New-VsanDiskGroup -SsdsAsCache"');
  }
  lines.push('Write-Host "Verify vSAN health in vCenter before proceeding."');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $VCenterServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- Final stage: workload test VMs ---

function buildWorkloadsDeploy(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const wl = spec.workloadVms;
  const nets = spec.networks;

  const vmNetPg = nets.vmTraffic ? 'Nested-VM-Traffic' : (nets.management ? 'Nested-Mgmt' : 'Nested-Mgmt');

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Final stage: Deploy test workload VM shells onto the vSAN cluster.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Prerequisites: vCenter up, vSAN cluster formed and healthy.');
  lines.push(`    Creates ${wl.count} blank VM shell${wl.count === 1 ? '' : 's'} (${wl.vcpu} vCPU / ${wl.vramGB}GB each) on the cluster.`);
  lines.push('    These VMs have no OS installed. They are useful for practising vMotion,');
  lines.push('    DRS, HA failover, and storage policy changes without needing live workloads.');
  lines.push('    To actually run something on them, power on and attach an OS ISO manually --');
  lines.push('    same interactive install pattern as the nested ESXi hosts.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    VM count: ${wl.count}    Size: ${wl.size} (${wl.vcpu} vCPU, ${wl.vramGB}GB RAM)`);
  lines.push(`    Network: ${vmNetPg}`);
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VCenterServer,');
  lines.push('');
  lines.push(`    [string]$DatacenterName = "${nc.datacenterName || 'Lab-DC'}",`);
  lines.push('');
  lines.push(`    [string]$ClusterName = "${nc.clusterName || 'mgmt-cluster'}",`);
  lines.push('');
  lines.push('    # Workload VMs land on the cluster default datastore (vSAN) unless overridden');
  lines.push('    [string]$Datastore = "",');
  lines.push('');
  lines.push('    [string]$VmFolder = "Nested-Lab",');
  lines.push('');
  lines.push(`    [string]$PortGroup = "${vmNetPg}"`,);
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('$vcCred = Get-Credential -Message "vCenter credentials"');
  lines.push('Connect-VIServer -Server $VCenterServer -Credential $vcCred | Out-Null');
  lines.push('');
  lines.push('$cluster = Get-Cluster -Name $ClusterName');
  lines.push('$vmHost = $cluster | Get-VMHost | Select-Object -First 1');
  lines.push('');
  lines.push('if ($Datastore) {');
  lines.push('    $ds = Get-Datastore -Name $Datastore');
  lines.push('} else {');
  lines.push('    $ds = Get-Datastore | Where-Object { $_.Type -eq "vsan" } | Select-Object -First 1');
  lines.push('    if (-not $ds) { $ds = $cluster | Get-VMHost | Get-Datastore | Select-Object -First 1 }');
  lines.push('}');
  lines.push('');
  lines.push('if (-not (Get-Folder -Name $VmFolder -ErrorAction SilentlyContinue)) {');
  lines.push('    $vmFolderParent = Get-Folder -Type VM -NoRecursion | Select-Object -First 1');
  lines.push('    New-Folder -Name $VmFolder -Location $vmFolderParent | Out-Null');
  lines.push('}');
  lines.push('');
  lines.push(`$vmCount = ${wl.count}`);
  lines.push(`$vcpu = ${wl.vcpu}`);
  lines.push(`$vramGB = ${wl.vramGB}`);
  lines.push('');
  lines.push('for ($i = 1; $i -le $vmCount; $i++) {');
  lines.push('    $vmName = "workload-{0:D2}" -f $i');
  lines.push('');
  lines.push('    if (Get-VM -Name $vmName -ErrorAction SilentlyContinue) {');
  lines.push('        Write-Host "$vmName already exists, skipping."');
  lines.push('        continue');
  lines.push('    }');
  lines.push('');
  lines.push('    $vm = New-VM -Name $vmName `');
  lines.push('        -VMHost $vmHost `');
  lines.push('        -Datastore $ds `');
  lines.push('        -DiskGB 40 `');
  lines.push('        -MemoryGB $vramGB `');
  lines.push('        -NumCpu $vcpu `');
  lines.push('        -GuestId "ubuntu64Guest" `');
  lines.push('        -Location $VmFolder');
  lines.push('');
  lines.push('    New-NetworkAdapter -VM $vm -NetworkName $PortGroup -Type Vmxnet3 -StartConnected | Out-Null');
  lines.push('');
  if (spec.nestedCluster.legacyCpuCompatibility) {
    lines.push('    New-AdvancedSetting -Entity $vm -Name "monitor.allowLegacyCPU" -Value "TRUE" -Confirm:$false | Out-Null');
    lines.push('');
  }
  lines.push('    Write-Host "Created $vmName ($vcpu vCPU / ${vramGB}GB) on $($ds.Name)"');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push(`Write-Host "${wl.count} workload VM shell${wl.count === 1 ? '' : 's'} created. Power them on for vMotion/DRS/HA practice."`);
  lines.push('Write-Host "To install an OS: attach an ISO to each VM via vCenter and boot."');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $VCenterServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- Jumpbox / WireGuard server VM shell ---

function buildJumpboxDeploy(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const ra = spec.remoteAccess;
  const nets = spec.networks;
  const isWgVm = ra.method === 'vpn' && ra.vpnType === 'wireguard';
  const vmDefault = isWgVm ? 'lab-wireguard' : 'lab-jumpbox';
  const role = isWgVm ? 'WireGuard VPN server' : 'SSH jump host';
  const mgmtPg = nets.management ? 'Nested-Mgmt' : (Object.values(nets).find(Boolean)?.name || 'Nested-Mgmt');

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push(`    Deploy a lightweight Linux VM to serve as the ${role}.`);
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Prerequisites: vCenter deployed, cluster formed.');
  lines.push('    VM spec: Ubuntu 22.04 LTS, 1 vCPU, 1GB RAM, 20GB disk.');
  lines.push('    The script also generates an ed25519 SSH keypair for access.');
  lines.push('    No ISO is attached -- use a cloud image or Ubuntu Server ISO manually.');
  lines.push('');
  lines.push('.NOTES');
  lines.push('    After creating this VM, install Ubuntu Server (attach ISO via vCenter).');
  lines.push('    Then add the public key to ~/.ssh/authorized_keys on the VM.');
  if (isWgVm) {
    lines.push('    Once Ubuntu is installed, copy wireguard-server.sh to the VM and run it as root.');
  }
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$VCenterServer,');
  lines.push('');
  lines.push(`    [string]$DatacenterName = "${nc.datacenterName || 'Lab-DC'}",`);
  lines.push('');
  lines.push(`    [string]$ClusterName = "${nc.clusterName || 'mgmt-cluster'}",`);
  lines.push('');
  lines.push('    # Leave blank to use the cluster default (vSAN if available)');
  lines.push('    [string]$Datastore = "",');
  lines.push('');
  lines.push(`    [string]$PortGroup = "${mgmtPg}",`);
  lines.push('');
  lines.push('    [string]$VmFolder = "Nested-Lab",');
  lines.push('');
  lines.push(`    [string]$VmName = "${vmDefault}",`);
  lines.push('');
  lines.push('    # Where the SSH keypair is written on this machine');
  lines.push(`    [string]$SshKeyPath = "$env:USERPROFILE\\.ssh\\${vmDefault}"`);
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('# --- Generate SSH keypair ---');
  lines.push('$sshKeygenAvailable = Get-Command ssh-keygen -ErrorAction SilentlyContinue');
  lines.push('if (-not $sshKeygenAvailable) {');
  lines.push('    Write-Warning "ssh-keygen not found. Install OpenSSH (Settings > Optional Features > OpenSSH Client)"');
  lines.push('    Write-Warning "or generate a keypair manually before connecting to the jumpbox."');
  lines.push('} elseif (-not (Test-Path $SshKeyPath)) {');
  lines.push('    $keyDir = Split-Path $SshKeyPath -Parent');
  lines.push('    if (-not (Test-Path $keyDir)) { New-Item -ItemType Directory -Path $keyDir | Out-Null }');
  lines.push('    ssh-keygen -t ed25519 -f $SshKeyPath -N "" -C "${VmName}@$(hostname)"');
  lines.push('    Write-Host ""');
  lines.push('    Write-Host "SSH keypair generated:"');
  lines.push('    Write-Host "  Private key: $SshKeyPath"');
  lines.push('    Write-Host "  Public key:  $SshKeyPath.pub"');
  lines.push('    Write-Host ""');
  lines.push('    Write-Host "IMPORTANT: Keep the private key secure. Do not commit it to version control."');
  lines.push('} else {');
  lines.push('    Write-Host "SSH keypair already exists at $SshKeyPath -- reusing it."');
  lines.push('}');
  lines.push('');
  lines.push('$pubKey = if (Test-Path "$SshKeyPath.pub") { Get-Content "$SshKeyPath.pub" } else { "<run ssh-keygen manually>" }');
  lines.push('');
  lines.push('# --- Connect to vCenter ---');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('$vcCred = Get-Credential -Message "vCenter credentials"');
  lines.push('Connect-VIServer -Server $VCenterServer -Credential $vcCred | Out-Null');
  lines.push('');
  lines.push('$cluster = Get-Cluster -Name $ClusterName');
  lines.push('$vmHost = $cluster | Get-VMHost | Select-Object -First 1');
  lines.push('');
  lines.push('if ($Datastore) {');
  lines.push('    $ds = Get-Datastore -Name $Datastore');
  lines.push('} else {');
  lines.push('    $ds = Get-Datastore | Where-Object { $_.Type -eq "vsan" } | Select-Object -First 1');
  lines.push('    if (-not $ds) { $ds = $cluster | Get-VMHost | Get-Datastore | Select-Object -First 1 }');
  lines.push('}');
  lines.push('');
  lines.push('if (-not (Get-Folder -Name $VmFolder -ErrorAction SilentlyContinue)) {');
  lines.push('    $vmFolderParent = Get-Folder -Type VM -NoRecursion | Select-Object -First 1');
  lines.push('    New-Folder -Name $VmFolder -Location $vmFolderParent | Out-Null');
  lines.push('}');
  lines.push('');
  lines.push('if (Get-VM -Name $VmName -ErrorAction SilentlyContinue) {');
  lines.push('    Write-Host "$VmName already exists, skipping VM creation."');
  lines.push('} else {');
  lines.push('    $vm = New-VM -Name $VmName `');
  lines.push('        -VMHost $vmHost `');
  lines.push('        -Datastore $ds `');
  lines.push('        -DiskGB 20 `');
  lines.push('        -MemoryGB 1 `');
  lines.push('        -NumCpu 1 `');
  lines.push('        -GuestId "ubuntu64Guest" `');
  lines.push('        -Location $VmFolder');
  lines.push('');
  lines.push(`    New-NetworkAdapter -VM $vm -NetworkName "${mgmtPg}" -Type Vmxnet3 -StartConnected | Out-Null`);
  lines.push('');
  if (spec.nestedCluster.legacyCpuCompatibility) {
    lines.push('    New-AdvancedSetting -Entity $vm -Name "monitor.allowLegacyCPU" -Value "TRUE" -Confirm:$false | Out-Null');
    lines.push('');
  }
  lines.push('    # Store the public key in VM notes -- easy to retrieve from vCenter UI after OS install');
  lines.push('    Set-VM -VM $vm -Notes "SSH public key for access:`n$pubKey`n`nAdd this to ~/.ssh/authorized_keys after OS install." -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('    Write-Host "Created: $VmName (1 vCPU / 1GB / 20GB on $($ds.Name))"');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Next steps:"');
  lines.push('Write-Host "  1. Power on $VmName in vCenter and install Ubuntu Server 22.04 LTS"');
  lines.push('Write-Host "  2. During or after install, add the public key to ~/.ssh/authorized_keys:"');
  lines.push('Write-Host "       $pubKey"');
  lines.push('Write-Host "  3. Connect: ssh -i $SshKeyPath <vm-ip>"');
  if (isWgVm) {
    lines.push('Write-Host "  4. Copy wireguard-server.sh to the VM and run it as root to set up WireGuard"');
  }
  lines.push('');
  lines.push('Disconnect-VIServer -Server $VCenterServer -Confirm:$false');
  lines.push('');

  return lines.join('\n');
}

// --- WireGuard server setup script (bash, runs on the jumpbox/WireGuard VM) ---

function buildWireGuardSetup(spec) {
  const lines = [];
  const nets = spec.networks;
  const mgmtCidr = nets.management?.cidr || '192.168.10.0/24';
  // WireGuard tunnel uses a separate /24 to avoid overlapping lab networks
  const wgSubnet = '10.200.0.0/24';
  const wgServerIp = '10.200.0.1';

  lines.push('#!/usr/bin/env bash');
  lines.push('# wireguard-server.sh');
  lines.push('# Run this as root on the jumpbox/WireGuard VM after Ubuntu 22.04 is installed.');
  lines.push('#');
  lines.push('# What this does:');
  lines.push('#   - Installs WireGuard');
  lines.push('#   - Generates the server keypair');
  lines.push('#   - Writes /etc/wireguard/wg0.conf');
  lines.push('#   - Enables IP forwarding so VPN clients can reach lab networks');
  lines.push('#   - Starts and enables the wg-quick@wg0 service');
  lines.push('#');
  lines.push('# After running this script, share the server public key with each client');
  lines.push('# and add client [Peer] blocks to /etc/wireguard/wg0.conf.');
  lines.push(`# Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push('if [ "$(id -u)" -ne 0 ]; then');
  lines.push('    echo "Run this as root: sudo bash wireguard-server.sh"');
  lines.push('    exit 1');
  lines.push('fi');
  lines.push('');
  lines.push('echo "Installing WireGuard..."');
  lines.push('apt-get update -qq && apt-get install -y -qq wireguard');
  lines.push('');
  lines.push('# Generate server keypair');
  lines.push('umask 077');
  lines.push('SERVER_PRIVATE_KEY=$(wg genkey)');
  lines.push('SERVER_PUBLIC_KEY=$(echo "$SERVER_PRIVATE_KEY" | wg pubkey)');
  lines.push('');
  lines.push('# Detect the default outbound interface (the one with internet/lab access)');
  lines.push('DEFAULT_IFACE=$(ip route show default | awk \'/default/ {print $5; exit}\')');
  lines.push('echo "Outbound interface: $DEFAULT_IFACE"');
  lines.push('');
  lines.push('cat > /etc/wireguard/wg0.conf << EOF');
  lines.push('[Interface]');
  lines.push(`Address = ${wgServerIp}/24`);
  lines.push('ListenPort = 51820');
  lines.push('PrivateKey = ${SERVER_PRIVATE_KEY}');
  lines.push('');
  lines.push('# NAT client traffic out to the lab network');
  lines.push('PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ${DEFAULT_IFACE} -j MASQUERADE');
  lines.push('PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ${DEFAULT_IFACE} -j MASQUERADE');
  lines.push('');
  lines.push('# ---- Add client peers below ----');
  lines.push('# Each peer looks like:');
  lines.push('#');
  lines.push('# [Peer]');
  lines.push('# # Human-readable comment');
  lines.push('# PublicKey = <client-public-key>');
  lines.push('# AllowedIPs = 10.200.0.X/32');
  lines.push('EOF');
  lines.push('');
  lines.push('chmod 600 /etc/wireguard/wg0.conf');
  lines.push('');
  lines.push('# Enable IP forwarding');
  lines.push('echo "net.ipv4.ip_forward=1" | tee -a /etc/sysctl.conf > /dev/null');
  lines.push('sysctl -p -q');
  lines.push('');
  lines.push('systemctl enable --now wg-quick@wg0');
  lines.push('');
  lines.push('echo ""');
  lines.push('echo "========================================"');
  lines.push('echo "  WireGuard VPN server is running"');
  lines.push('echo "========================================"');
  lines.push('echo "Server public key: ${SERVER_PUBLIC_KEY}"');
  lines.push(`echo "VPN subnet:        ${wgSubnet}  (server is ${wgServerIp})"`);
  lines.push('echo "Listen port:       51820"');
  lines.push('echo ""');
  lines.push('echo "To add a client peer:"');
  lines.push('echo "  1. On the client: wg genkey | tee client.key | wg pubkey > client.pub"');
  lines.push('echo "  2. Add to /etc/wireguard/wg0.conf on this server:"');
  lines.push('echo "       [Peer]"');
  lines.push('echo "       PublicKey = $(cat client.pub)"');
  lines.push('echo "       AllowedIPs = 10.200.0.X/32"');
  lines.push('echo "  3. Reload: wg syncconf wg0 <(wg-quick strip wg0)"');
  lines.push(`echo "  4. Client wg0.conf AllowedIPs should include ${mgmtCidr} to reach lab hosts"`);
  lines.push('echo ""');
  lines.push('echo "See lab-design.md for the full client configuration template."');

  return lines.join('\n');
}

// --- VyOS site-to-site WireGuard tunnel config ---

function buildVyosSiteToSite(spec) {
  const lines = [];
  const nets = spec.networks;
  const mgmtCidr = nets.management?.cidr || '192.168.10.0/24';

  lines.push('# vyos-site-to-site.conf');
  lines.push('# VyOS WireGuard site-to-site tunnel configuration.');
  lines.push('# Paste these commands into the VyOS CLI after the base config');
  lines.push('# (NAT, DHCP, DNS) is working. Requires VyOS 1.4 (Sagitta) or later.');
  lines.push(`# Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('#');
  lines.push('# BEFORE RUNNING:');
  lines.push('# Step 1 -- Generate a WireGuard keypair on this VyOS router:');
  lines.push('#   run generate pki wireguard key-pair');
  lines.push('#   Copy the "Private Key" value for use in the private-key line below.');
  lines.push('#   Share the "Public Key" value with the operator at the remote site.');
  lines.push('#');
  lines.push('# Step 2 -- Get the remote site\'s WireGuard public key and endpoint IP.');
  lines.push('#   Fill in <remote-public-key> and <remote-endpoint-ip> below.');
  lines.push('');
  lines.push('# --- Tunnel interface ---');
  lines.push('set interfaces wireguard wg0 description \'Site-to-site VPN\'');
  lines.push("set interfaces wireguard wg0 address '10.201.0.1/30'");
  lines.push("set interfaces wireguard wg0 port '51821'");
  lines.push("set interfaces wireguard wg0 private-key '<paste-private-key-here>'");
  lines.push('');
  lines.push('# --- Remote peer ---');
  lines.push("set interfaces wireguard wg0 peer remote-site public-key '<remote-public-key>'");
  lines.push("set interfaces wireguard wg0 peer remote-site address '<remote-endpoint-ip>'");
  lines.push("set interfaces wireguard wg0 peer remote-site port '51821'");
  lines.push("set interfaces wireguard wg0 peer remote-site allowed-ips '0.0.0.0/0'");
  lines.push('');
  lines.push('# --- Route remote network over the tunnel ---');
  lines.push('# Replace 192.168.100.0/24 with the actual subnet at the remote site.');
  lines.push("set protocols static route 192.168.100.0/24 interface wg0");
  lines.push('');
  lines.push('# --- Firewall: allow WireGuard on the WAN interface ---');
  lines.push("set firewall name WAN_LOCAL rule 20 action accept");
  lines.push("set firewall name WAN_LOCAL rule 20 description 'WireGuard site-to-site'");
  lines.push("set firewall name WAN_LOCAL rule 20 destination port 51821");
  lines.push("set firewall name WAN_LOCAL rule 20 protocol udp");
  lines.push('');
  lines.push('commit');
  lines.push('save');
  lines.push('');
  lines.push('# --- Verify ---');
  lines.push('# After both sides are configured, check the tunnel status:');
  lines.push('#   run show interfaces wireguard wg0');
  lines.push('#   run ping 10.201.0.2    # remote tunnel endpoint');
  lines.push(`#   run ping <ip-in-${mgmtCidr}>  # host in lab management network`);

  return lines.join('\n');
}

// --- NVMe memory tiering configuration ---

function buildMemoryTiering(spec) {
  const lines = [];
  const nc = spec.nestedCluster;
  const mt = nc.memoryTiering;
  const nets = spec.networks;
  const dc = spec.domainController || {};

  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Optional stage: Add NVMe tier VMDKs to nested hosts and configure ESXi memory tiering.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Prerequisites: vSAN cluster formed and healthy (run after vsan-cluster.ps1).');
  lines.push('');
  lines.push('    Phase 1 (this script): Adds a virtual NVMe disk to each nested ESXi host VM');
  lines.push('    on the physical host. Run this while connected to the PHYSICAL ESXi host.');
  lines.push('');
  lines.push('    Phase 2 (manual, per-host): After adding the disk, put each nested host into');
  lines.push('    maintenance mode and run the esxcli commands below to configure tiering.');
  lines.push('    Memory tiering shows Configured=TRUE immediately, but Runtime=FALSE until the');
  lines.push('    host exits maintenance mode and reboots.');
  lines.push('');
  lines.push('.NOTES');
  lines.push(`    NVMe disk per host: ${mt.nvmeSizeGB}GB`);
  lines.push(`    Memory tier percentage: ${mt.tierNvmePct}%`);
  lines.push(`    Nested host count: ${nc.hostCount}`);
  lines.push(`    Total NVMe storage needed: ${nc.hostCount * mt.nvmeSizeGB}GB`);
  lines.push('    These are virtual NVMe disks -- they behave like NVMe inside nested ESXi');
  lines.push('    but consume space from the physical host datastore like any other VMDK.');
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    # Physical ESXi host that runs the nested host VMs');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$PhysicalESXiHost,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$Datastore,');
  lines.push('');
  lines.push(`    [int]$NvmeSizeGB = ${mt.nvmeSizeGB},`);
  lines.push('');
  lines.push('    [string]$VmNamePrefix = "nested-esxi-"');
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI module not found. Install it first: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('');
  lines.push('$cred = Get-Credential -Message "Physical ESXi host credentials"');
  lines.push('Connect-VIServer -Server $PhysicalESXiHost -Credential $cred | Out-Null');
  lines.push('');
  lines.push('$ds = Get-Datastore -Name $Datastore');
  lines.push('');
  lines.push(`$hostNames = 1..${nc.hostCount} | ForEach-Object { "{0}{1:D2}" -f $VmNamePrefix, $_ }`);
  lines.push('');
  lines.push('foreach ($vmName in $hostNames) {');
  lines.push('    $vm = Get-VM -Name $vmName -ErrorAction SilentlyContinue');
  lines.push('    if (-not $vm) {');
  lines.push('        Write-Warning "VM $vmName not found — skipping."');
  lines.push('        continue');
  lines.push('    }');
  lines.push('');
  lines.push('    Write-Host "Adding ${NvmeSizeGB}GB NVMe VMDK to $vmName ..."');
  lines.push('');
  lines.push('    # Add a virtual NVMe controller if one does not exist');
  lines.push('    $vmView = $vm.ExtensionData');
  lines.push('    $hasNvme = $vmView.Config.Hardware.Device | Where-Object { $_ -is [VMware.Vim.VirtualNVMEController] }');
  lines.push('');
  lines.push('    $configSpec = New-Object VMware.Vim.VirtualMachineConfigSpec');
  lines.push('    $devChanges  = @()');
  lines.push('');
  lines.push('    if (-not $hasNvme) {');
  lines.push('        $nvmeCtrl = New-Object VMware.Vim.VirtualNVMEController');
  lines.push('        $nvmeCtrl.key       = -100');
  lines.push('        $nvmeCtrl.busNumber = 0');
  lines.push('        $ctrlSpec           = New-Object VMware.Vim.VirtualDeviceConfigSpec');
  lines.push('        $ctrlSpec.device    = $nvmeCtrl');
  lines.push('        $ctrlSpec.operation = [VMware.Vim.VirtualDeviceConfigSpecOperation]::add');
  lines.push('        $devChanges        += $ctrlSpec');
  lines.push('    } else {');
  lines.push('        $nvmeCtrl     = $hasNvme | Select-Object -First 1');
  lines.push('        $nvmeCtrl.key = $nvmeCtrl.key');
  lines.push('    }');
  lines.push('');
  lines.push('    # Add NVMe disk on the controller');
  lines.push('    $disk                      = New-Object VMware.Vim.VirtualDisk');
  lines.push('    $disk.key                  = -101');
  lines.push('    $disk.controllerKey        = -100');
  lines.push('    $disk.unitNumber           = 0');
  lines.push('    $disk.capacityInKB         = $NvmeSizeGB * 1MB');
  lines.push('    $backing                   = New-Object VMware.Vim.VirtualDiskFlatVer2BackingInfo');
  lines.push('    $backing.diskMode          = "persistent"');
  lines.push('    $backing.thinProvisioned   = $true');
  lines.push('    $backing.fileName          = ""');
  lines.push('    $disk.backing              = $backing');
  lines.push('    $diskSpec                  = New-Object VMware.Vim.VirtualDeviceConfigSpec');
  lines.push('    $diskSpec.device           = $disk');
  lines.push('    $diskSpec.operation        = [VMware.Vim.VirtualDeviceConfigSpecOperation]::add');
  lines.push('    $diskSpec.fileOperation    = [VMware.Vim.VirtualDeviceConfigSpecFileOperation]::create');
  lines.push('    $devChanges               += $diskSpec');
  lines.push('');
  lines.push('    $configSpec.deviceChange = $devChanges');
  lines.push('    $task = $vmView.ReconfigVM_Task($configSpec)');
  lines.push('    $task | Wait-Task | Out-Null');
  lines.push('    Write-Host "  Done: $vmName — NVMe VMDK added."');
  lines.push('}');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $PhysicalESXiHost -Confirm:$false');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Phase 1 complete. NVMe VMDKs added to all nested hosts."');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Phase 2 (manual) — run on each nested host via esxcli or SSH:"');
  lines.push('Write-Host ""');
  lines.push('Write-Host "  1. Put host in maintenance mode"');
  lines.push('Write-Host "  2. SSH into the nested host and run:"');
  lines.push('Write-Host ""');
  lines.push(`Write-Host "     # Enable early memory reservation (required for tiering)"`);
  lines.push('Write-Host "     esxcli system settings advanced set -o /Mem/MemEarlyReserve -i 1"');
  lines.push('Write-Host ""');
  lines.push(`Write-Host "     # Find the NVMe device path (look for the ~${mt.nvmeSizeGB}GB device)"`);
  lines.push('Write-Host "     esxcli storage core device list | grep -A5 capacity"');
  lines.push('Write-Host ""');
  lines.push('Write-Host "     # Add the NVMe device as a memory tier"');
  lines.push('Write-Host "     esxcli system memtiering add --device /vmfs/devices/disks/<nvme-device-naa>"');
  lines.push('Write-Host ""');
  lines.push(`Write-Host "     # Set the tier percentage (${mt.tierNvmePct}% of host memory becomes NVMe-backed)"`);
  lines.push(`Write-Host "     esxcli system memtiering set --enable 1 --tier-nvme-pct ${mt.tierNvmePct}"`);
  lines.push('Write-Host ""');
  lines.push('Write-Host "  3. Exit maintenance mode — the host will reboot to apply the NVMe tier."');
  lines.push('Write-Host "     After reboot: Configured=TRUE, Runtime=TRUE."');
  lines.push('Write-Host "     Before reboot: Configured=TRUE, Runtime=FALSE — this is expected."');
  lines.push('');

  return lines.join('\n');
}

module.exports = { buildPowerShellScripts };
