// lib/generateDepot.js
//
// Generates the four depot-related output files:
//   depot-deploy.ps1        -- Linux VM shell (nginx mode)
//   depot-configure.sh      -- nginx HTTPS setup script (nginx mode)
//   depot-iis.ps1           -- IIS setup on existing DC (iis mode)
//   depot-instructions.md   -- bundle layout, download guide, SDDC Manager trust steps

function buildDepotDeploy(spec) {
  const depot = spec.bundleDepot;
  const mgmtPg = 'Nested-Trunk';

  const lines = [];
  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Deploy the VCF bundle depot VM (nginx/Linux).');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Creates a lightweight Linux VM shell (lab-depot) for hosting the VCF bundle depot.');
  lines.push('    The VM is placed on host 1\'s local datastore. After deploy, install Ubuntu/Debian,');
  lines.push('    copy depot-configure.sh to the VM, and run it as root to configure nginx.');
  lines.push('');
  lines.push('.NOTES');
  lines.push('    VM sizing: 2 vCPU / 4GB RAM / 100GB disk (minimum for hosting bundle files).');
  lines.push('    Depot IP: ' + (depot.ipAddress || '<set in wizard>'));
  lines.push('#>');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$PhysicalESXiHost,');
  lines.push('');
  lines.push('    [Parameter(Mandatory = $true)]');
  lines.push('    [string]$Datastore,');
  lines.push('');
  lines.push('    [string]$LinuxIsoPath,');
  lines.push('');
  lines.push(`    [string]$PortGroup = "${mgmtPg}"`);
  lines.push(')');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');
  lines.push('if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {');
  lines.push('    throw "VMware.PowerCLI not found. Install it: Install-Module VMware.PowerCLI -Scope CurrentUser"');
  lines.push('}');
  lines.push('');
  lines.push('Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null');
  lines.push('$cred = Get-Credential -Message "Physical ESXi root credentials"');
  lines.push('Connect-VIServer -Server $PhysicalESXiHost -Credential $cred | Out-Null');
  lines.push('Write-Host "Connected to physical host: $PhysicalESXiHost"');
  lines.push('');
  lines.push('$ds = Get-Datastore -Name $Datastore -ErrorAction Stop');
  lines.push('');
  lines.push('# --- Create depot VM ---');
  lines.push('if (Get-VM -Name "lab-depot" -ErrorAction SilentlyContinue) {');
  lines.push('    Write-Host "lab-depot already exists -- skipping creation."');
  lines.push('} else {');
  lines.push('    Write-Host "Creating lab-depot VM..."');
  lines.push('    New-VM -Name "lab-depot" `');
  lines.push('           -Datastore $ds `');
  lines.push('           -NumCpu 2 `');
  lines.push('           -MemoryGB 4 `');
  lines.push('           -DiskGB 100 `');
  lines.push('           -DiskStorageFormat Thin `');
  lines.push('           -GuestId "ubuntu64Guest" `');
  lines.push('           -NetworkName $PortGroup | Out-Null');
  lines.push('    Write-Host "lab-depot VM created."');
  lines.push('}');
  lines.push('');
  lines.push('$vm = Get-VM -Name "lab-depot"');
  lines.push('');
  lines.push('# Ensure nested virtualisation flag is off (this is a service VM, not nested ESXi)');
  lines.push('$vmConfig = New-Object VMware.Vim.VirtualMachineConfigSpec');
  lines.push('$vmConfig.nestedHVEnabled = $false');
  lines.push('$vm.ExtensionData.ReconfigVM($vmConfig)');
  lines.push('');
  lines.push('if ($LinuxIsoPath) {');
  lines.push('    Write-Host "Attaching Linux ISO..."');
  lines.push('    $isoDs = "[" + $ds.Name + "] " + ($LinuxIsoPath -replace "^.*\[.*?\]\s*", "")');
  lines.push('    Get-CDDrive -VM $vm | Set-CDDrive -IsoPath $LinuxIsoPath -StartConnected $true -Confirm:$false | Out-Null');
  lines.push('    Write-Host "ISO attached."');
  lines.push('}');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "lab-depot created. Next steps:"');
  lines.push('Write-Host "  1. Power on the VM and install Ubuntu Server 22.04 LTS"');
  lines.push('Write-Host "  2. Assign static IP: ' + (depot.ipAddress || '<depot-ip>') + '"');
  lines.push('Write-Host "  3. Copy depot-configure.sh to the VM and run: sudo bash depot-configure.sh"');
  lines.push('Write-Host "  4. Follow depot-instructions.md to populate the bundle folders"');
  lines.push('');
  lines.push('Disconnect-VIServer -Server $PhysicalESXiHost -Confirm:$false');

  return lines.join('\n');
}

function buildDepotConfigure(spec) {
  const depot = spec.bundleDepot;
  const depotIp = depot.ipAddress || '192.168.10.20';

  const lines = [];
  lines.push('#!/bin/bash');
  lines.push('# depot-configure.sh');
  lines.push('# Run on the depot VM as root after Ubuntu/Debian install.');
  lines.push(`# Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('#');
  lines.push('# Configures nginx as an HTTPS file server for VCF bundle hosting.');
  lines.push('# Self-signed cert is valid 10 years. SDDC Manager must trust this cert');
  lines.push('# before bring-up -- see depot-instructions.md for the trust steps.');
  lines.push('');
  lines.push('set -e');
  lines.push('');
  lines.push(`DEPOT_IP="${depotIp}"`);
  lines.push('DEPOT_ROOT="/var/www/html/depot"');
  lines.push('CERT_DIR="/etc/nginx/ssl"');
  lines.push('');
  lines.push('echo "=== Installing nginx and openssl ==="');
  lines.push('apt-get update -q');
  lines.push('apt-get install -y nginx openssl');
  lines.push('');
  lines.push('echo "=== Generating self-signed TLS certificate ==="');
  lines.push('mkdir -p "$CERT_DIR"');
  lines.push('openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \\');
  lines.push('  -keyout "$CERT_DIR/depot.key" \\');
  lines.push('  -out "$CERT_DIR/depot.crt" \\');
  lines.push('  -subj "/CN=${DEPOT_IP}/O=Lab Bundle Depot/C=US" \\');
  lines.push('  -addext "subjectAltName=IP:${DEPOT_IP}"');
  lines.push('chmod 600 "$CERT_DIR/depot.key"');
  lines.push('');
  lines.push('echo "=== Creating depot folder structure ==="');
  lines.push('mkdir -p "$DEPOT_ROOT"/{esxi,vcenter,nsx,sddc-manager,vrealize,tools}');
  lines.push('chown -R www-data:www-data /var/www/html/depot');
  lines.push('');
  lines.push('echo "=== Writing nginx configuration ==="');
  lines.push('cat > /etc/nginx/sites-available/depot << \'NGINXCONF\'');
  lines.push('server {');
  lines.push('    listen 80;');
  lines.push('    return 301 https://$host$request_uri;');
  lines.push('}');
  lines.push('');
  lines.push('server {');
  lines.push('    listen 443 ssl;');
  lines.push('    server_name _;');
  lines.push('');
  lines.push('    ssl_certificate     /etc/nginx/ssl/depot.crt;');
  lines.push('    ssl_certificate_key /etc/nginx/ssl/depot.key;');
  lines.push('    ssl_protocols       TLSv1.2 TLSv1.3;');
  lines.push('');
  lines.push('    root /var/www/html;');
  lines.push('');
  lines.push('    location /depot/ {');
  lines.push('        autoindex on;');
  lines.push('        autoindex_exact_size off;');
  lines.push('        autoindex_localtime on;');
  lines.push('    }');
  lines.push('}');
  lines.push('NGINXCONF');
  lines.push('');
  lines.push('ln -sf /etc/nginx/sites-available/depot /etc/nginx/sites-enabled/depot');
  lines.push('rm -f /etc/nginx/sites-enabled/default');
  lines.push('');
  lines.push('nginx -t');
  lines.push('systemctl restart nginx');
  lines.push('systemctl enable nginx');
  lines.push('');
  lines.push('echo ""');
  lines.push('echo "=== Depot configured ==="');
  lines.push(`echo "URL:  https://${depotIp}/depot/"`);
  lines.push('echo "Cert: $CERT_DIR/depot.crt"');
  lines.push('echo ""');
  lines.push('echo "Export the certificate for SDDC Manager trust:"');
  lines.push('echo "  openssl x509 -in $CERT_DIR/depot.crt -out ~/depot-ca.pem"');
  lines.push('echo "Then follow depot-instructions.md to add it as a trusted CA in SDDC Manager."');

  return lines.join('\n');
}

function buildDepotIis(spec) {
  const depot = spec.bundleDepot;
  const dc = spec.domainController;
  const depotIp = depot.ipAddress || '<depot-ip>';

  const lines = [];
  lines.push('<#');
  lines.push('.SYNOPSIS');
  lines.push('    Configure IIS on the domain controller as a VCF bundle depot.');
  lines.push('');
  lines.push('.DESCRIPTION');
  lines.push(`    Generated by vsphere-lab-wizard on ${spec.generatedAt}.`);
  lines.push('    Run on the domain controller VM as a local administrator.');
  lines.push('    Installs IIS, creates a self-signed HTTPS cert, creates the depot folder');
  lines.push('    structure under wwwroot, and enables directory browsing.');
  lines.push('    SDDC Manager must trust the self-signed cert before bring-up --');
  lines.push('    see depot-instructions.md for the trust steps.');
  lines.push('#>');
  lines.push('');
  lines.push('#Requires -RunAsAdministrator');
  lines.push('');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push(`$DepotIp = "${depotIp}"`);
  lines.push('$DepotRoot = "C:\\inetpub\\wwwroot\\depot"');
  lines.push('$CertPath  = "C:\\LabDepot\\depot-ca.cer"');
  lines.push('');
  lines.push('Write-Host "=== Installing IIS and management tools ==="');
  lines.push('$features = @(');
  lines.push("    'Web-Server', 'Web-Common-Http', 'Web-Default-Doc',");
  lines.push("    'Web-Dir-Browsing', 'Web-Http-Errors', 'Web-Static-Content',");
  lines.push("    'Web-Http-Logging', 'Web-Stat-Compression', 'Web-Filtering',");
  lines.push("    'Web-Mgmt-Console', 'Web-Scripting-Tools'");
  lines.push(')');
  lines.push('Install-WindowsFeature -Name $features -IncludeManagementTools | Out-Null');
  lines.push('Write-Host "IIS installed."');
  lines.push('');
  lines.push('Write-Host "=== Creating self-signed TLS certificate ==="');
  lines.push('New-Item -ItemType Directory -Path (Split-Path $CertPath) -Force | Out-Null');
  lines.push('$cert = New-SelfSignedCertificate `');
  lines.push('    -DnsName $DepotIp `');
  lines.push('    -CertStoreLocation "cert:\\LocalMachine\\My" `');
  lines.push('    -NotAfter (Get-Date).AddYears(10) `');
  lines.push('    -KeyUsage DigitalSignature, KeyEncipherment `');
  lines.push('    -FriendlyName "Lab Depot TLS"');
  lines.push('');
  lines.push('# Export the public cert for distribution to SDDC Manager');
  lines.push('Export-Certificate -Cert $cert -FilePath $CertPath -Type CERT | Out-Null');
  lines.push('Write-Host "Certificate created. Thumbprint: $($cert.Thumbprint)"');
  lines.push('Write-Host "Public cert exported to: $CertPath"');
  lines.push('');
  lines.push('Write-Host "=== Creating depot folder structure ==="');
  lines.push('$folders = @("esxi", "vcenter", "nsx", "sddc-manager", "vrealize", "tools")');
  lines.push('foreach ($f in $folders) {');
  lines.push('    New-Item -ItemType Directory -Path "$DepotRoot\\$f" -Force | Out-Null');
  lines.push('}');
  lines.push('Write-Host "Depot folders created under $DepotRoot"');
  lines.push('');
  lines.push('Write-Host "=== Configuring IIS HTTPS binding ==="');
  lines.push('Import-Module WebAdministration');
  lines.push('');
  lines.push('# Remove any existing HTTPS binding on 443 and add ours');
  lines.push('$site = Get-Website -Name "Default Web Site"');
  lines.push('$existingHttps = $site.bindings.Collection | Where-Object { $_.protocol -eq "https" }');
  lines.push('if ($existingHttps) { Remove-WebBinding -Name "Default Web Site" -Protocol https }');
  lines.push('');
  lines.push('New-WebBinding -Name "Default Web Site" -Protocol https -Port 443 -IPAddress "*"');
  lines.push('$binding = Get-WebBinding -Name "Default Web Site" -Protocol https');
  lines.push('$binding.AddSslCertificate($cert.Thumbprint, "My")');
  lines.push('');
  lines.push('# Enable directory browsing');
  lines.push('Set-WebConfigurationProperty -Filter "system.webServer/directoryBrowse" `');
  lines.push('    -Name "enabled" -Value $true -PSPath "IIS:\\Sites\\Default Web Site"');
  lines.push('');
  lines.push('# Set depot as a virtual directory');
  lines.push('New-WebVirtualDirectory -Site "Default Web Site" -Name "depot" -PhysicalPath $DepotRoot -Force | Out-Null');
  lines.push('');
  lines.push('# Grant IIS_IUSRS read access to the depot root');
  lines.push('$acl = Get-Acl $DepotRoot');
  lines.push('$rule = New-Object Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow")');
  lines.push('$acl.AddAccessRule($rule)');
  lines.push('Set-Acl $DepotRoot $acl');
  lines.push('');
  lines.push('Restart-WebAppPool -Name "DefaultAppPool"');
  lines.push('iisreset /noforce | Out-Null');
  lines.push('');
  lines.push('Write-Host ""');
  lines.push('Write-Host "=== IIS depot configured ==="');
  lines.push(`Write-Host "URL:  https://${depotIp}/depot/"`);
  lines.push('Write-Host "Cert: $CertPath"');
  lines.push('Write-Host ""');
  lines.push('Write-Host "Next steps:"');
  lines.push('Write-Host "  1. Copy $CertPath to the SDDC Manager appliance"');
  lines.push('Write-Host "  2. Follow depot-instructions.md to trust the cert in SDDC Manager"');
  lines.push('Write-Host "  3. Populate the depot folders with VCF bundles (see depot-instructions.md)"');

  return lines.join('\n');
}

function buildDepotInstructions(spec) {
  const depot = spec.bundleDepot;
  const isLinux = depot.mode !== 'iis';
  const depotIp = depot.ipAddress || '<depot-ip>';
  const depotUrl = `https://${depotIp}/depot`;

  const lines = [];
  lines.push('# VCF Bundle Depot Instructions');
  lines.push('');
  lines.push(`*Generated by vsphere-lab-wizard on ${spec.generatedAt}*`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## What the depot is and why it exists');
  lines.push('');
  lines.push('When SDDC Manager performs a VCF bring-up or lifecycle update, it downloads bundle files');
  lines.push('from Broadcom\'s CDN. In a lab environment this creates two problems:');
  lines.push('');
  lines.push('1. **Slow downloads** -- VCF bundles are large (ESXi bundle alone is ~2-4 GB; the full');
  lines.push('   BOM for a bring-up can exceed 20 GB). Downloading each run over the internet is slow.');
  lines.push('2. **Air-gapped or restricted environments** -- some lab setups have no internet path');
  lines.push('   from the management network.');
  lines.push('');
  lines.push('A local depot hosts the bundles on your LAN. SDDC Manager downloads at 1 GbE / 10 GbE');
  lines.push('speeds instead of WAN. The depot URL is registered in SDDC Manager once, and SDDC Manager');
  lines.push('checks it before going to the internet.');
  lines.push('');
  lines.push('The depot for this lab is:');
  lines.push('');
  lines.push(`    ${depotUrl}/`);
  lines.push('');
  lines.push(`Hosted by: **${isLinux ? `lab-depot (Linux/nginx) at ${depotIp}` : `domain controller (Windows/IIS) at ${depotIp}`}**`);
  lines.push('');
  lines.push('> **Scope note:** This wizard sets up the depot server infrastructure. Downloading the');
  lines.push('> actual VCF bundles from Broadcom and populating the depot folders is a manual step');
  lines.push('> covered in this document. VCF bring-up itself is a separate process and is out of');
  lines.push('> scope for v1 of this wizard.');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Step 1 -- Download VCF bundles from Broadcom');
  lines.push('');
  lines.push('You need a Broadcom portal account: https://support.broadcom.com');
  lines.push('');
  lines.push('Navigate to: **My Downloads → VMware Cloud Foundation**');
  lines.push('');
  lines.push('Download the bundles for your target VCF version. The exact filenames vary by release;');
  lines.push('the table below shows what each bundle type is called and where it goes:');
  lines.push('');
  lines.push('| Bundle type | Filename pattern | Depot subfolder |');
  lines.push('|-------------|-----------------|-----------------|');
  lines.push('| ESXi image bundle | `VMware-ESXi-*.zip` | `esxi/` |');
  lines.push('| vCenter appliance bundle | `VMware-vCenter-Server-Appliance-*.zip` | `vcenter/` |');
  lines.push('| NSX appliance bundle | `VMware-NSX-*.zip` | `nsx/` |');
  lines.push('| SDDC Manager bundle | `VMware-SDDC-Manager-*.zip` | `sddc-manager/` |');
  lines.push('| Tools / utilities | `VMware-VCF-*.zip` | `tools/` |');
  lines.push('');
  lines.push('Not all bundles are needed for every operation -- a basic bring-up needs ESXi, vCenter,');
  lines.push('NSX, and SDDC Manager. Download the full set for your VCF version.');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Step 2 -- Populate the depot folders');
  lines.push('');
  if (isLinux) {
    lines.push('Copy bundles to the depot VM via SCP or rsync:');
    lines.push('');
    lines.push('```bash');
    lines.push(`scp VMware-ESXi-*.zip ubuntu@${depotIp}:/var/www/html/depot/esxi/`);
    lines.push(`scp VMware-vCenter-*.zip ubuntu@${depotIp}:/var/www/html/depot/vcenter/`);
    lines.push(`scp VMware-NSX-*.zip ubuntu@${depotIp}:/var/www/html/depot/nsx/`);
    lines.push(`scp VMware-SDDC-Manager-*.zip ubuntu@${depotIp}:/var/www/html/depot/sddc-manager/`);
    lines.push('```');
    lines.push('');
    lines.push('After copying, fix ownership:');
    lines.push('');
    lines.push('```bash');
    lines.push(`ssh ubuntu@${depotIp} "sudo chown -R www-data:www-data /var/www/html/depot"`);
    lines.push('```');
  } else {
    lines.push('Copy bundles to the depot root on the domain controller:');
    lines.push('');
    lines.push('```powershell');
    lines.push('# From a machine with access to the DC');
    lines.push(`$dc = "${depotIp}"`);
    lines.push('Copy-Item VMware-ESXi-*.zip          "\\\\$dc\\C$\\inetpub\\wwwroot\\depot\\esxi\\"');
    lines.push('Copy-Item VMware-vCenter-*.zip        "\\\\$dc\\C$\\inetpub\\wwwroot\\depot\\vcenter\\"');
    lines.push('Copy-Item VMware-NSX-*.zip            "\\\\$dc\\C$\\inetpub\\wwwroot\\depot\\nsx\\"');
    lines.push('Copy-Item VMware-SDDC-Manager-*.zip   "\\\\$dc\\C$\\inetpub\\wwwroot\\depot\\sddc-manager\\"');
    lines.push('```');
  }
  lines.push('');
  lines.push('Verify directory browsing works before configuring SDDC Manager:');
  lines.push('');
  lines.push(`Open \`${depotUrl}/esxi/\` in a browser -- you should see a directory listing.`);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Step 3 -- Trust the depot certificate in SDDC Manager');
  lines.push('');
  lines.push('The depot uses a self-signed TLS certificate. SDDC Manager validates the cert before');
  lines.push('downloading from the depot, so you must add it as a trusted CA first.');
  lines.push('');
  if (isLinux) {
    lines.push('**Export the certificate from the depot VM:**');
    lines.push('');
    lines.push('```bash');
    lines.push(`ssh ubuntu@${depotIp} "sudo openssl x509 -in /etc/nginx/ssl/depot.crt -out ~/depot-ca.pem"`);
    lines.push(`scp ubuntu@${depotIp}:~/depot-ca.pem ./depot-ca.pem`);
    lines.push('```');
  } else {
    lines.push('The certificate was exported to `C:\\LabDepot\\depot-ca.cer` by `depot-iis.ps1`.');
    lines.push('Copy it to your workstation:');
    lines.push('');
    lines.push('```powershell');
    lines.push(`Copy-Item "\\\\${depotIp}\\C$\\LabDepot\\depot-ca.cer" .\\depot-ca.cer`);
    lines.push('```');
  }
  lines.push('');
  lines.push('**Add the certificate to SDDC Manager:**');
  lines.push('');
  lines.push('1. Log in to SDDC Manager UI → **Administration → Certificate Management → Trusted Certificates**');
  lines.push('2. Click **Import Certificate**');
  lines.push('3. Upload `depot-ca.pem` / `depot-ca.cer`');
  lines.push('4. Click **Save**');
  lines.push('');
  lines.push('Alternatively, via the SDDC Manager CLI:');
  lines.push('');
  lines.push('```bash');
  lines.push('# SSH to SDDC Manager as vcf');
  lines.push('scp depot-ca.pem vcf@<sddc-manager-ip>:~/');
  lines.push('ssh vcf@<sddc-manager-ip>');
  lines.push('sudo /usr/lib/vmware-sddc-manager/bin/sddc-manager-cert trust --cert ~/depot-ca.pem');
  lines.push('```');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Step 4 -- Register the depot URL in SDDC Manager');
  lines.push('');
  lines.push('1. Log in to SDDC Manager UI');
  lines.push('2. Navigate to **Administration → Bundle Management → Local Depot Settings**');
  lines.push('3. Enter the depot URL:');
  lines.push('');
  lines.push(`    \`${depotUrl}\``);
  lines.push('');
  lines.push('4. Click **Save and Validate** -- SDDC Manager will test connectivity to the depot');
  lines.push('5. Once validated, navigate to **Lifecycle Management → Bundle Transfer** to initiate');
  lines.push('   transfers from the depot to SDDC Manager');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Folder structure reference');
  lines.push('');
  lines.push('```');
  lines.push(`${depotUrl}/`);
  lines.push('├── esxi/              VMware-ESXi-*.zip');
  lines.push('├── vcenter/           VMware-vCenter-Server-Appliance-*.zip');
  lines.push('├── nsx/               VMware-NSX-*.zip');
  lines.push('├── sddc-manager/      VMware-SDDC-Manager-*.zip');
  lines.push('├── vrealize/          VMware-vRA-*.zip  (if needed)');
  lines.push('└── tools/             Other utility bundles');
  lines.push('```');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('## Further reading');
  lines.push('');
  lines.push('William Lam has documented the local depot pattern in detail, including the VCF');
  lines.push('bring-up flow and bundle management:');
  lines.push('');
  lines.push('**https://williamlam.com** -- search for "VCF local depot" or "SDDC Manager bundle"');
  lines.push('');
  lines.push('VMware official docs:');
  lines.push('https://docs.broadcom.com/doc/vmware-cloud-foundation → Bundle Management');

  return lines.join('\n');
}

function buildDepotFiles(spec) {
  const depot = spec.bundleDepot;
  if (!depot || !depot.enabled) return {};

  const files = {};
  files['depot-instructions.md'] = buildDepotInstructions(spec);

  if (depot.mode === 'iis') {
    files['depot-iis.ps1'] = buildDepotIis(spec);
  } else {
    files['depot-deploy.ps1'] = buildDepotDeploy(spec);
    files['depot-configure.sh'] = buildDepotConfigure(spec);
  }

  return files;
}

module.exports = { buildDepotFiles, buildDepotInstructions };
